### ISSUE TITLE
--retain-info not working as expected

### ISSUE THREAD

**Issue by srinipr4** [mskcc/vcf2maf#104]
The columns specified appear in the header row but the actual values for the individual rows remain unpopulated.

command (had to rename .vcf to .txt for uploading):
```bash
perl vcf2maf.pl --input-vcf input_to_vep_head.txt --output-maf input_to_vep_head.vep.maf --retain-info SAMPLE,OrigChrom,OrigStart,OrigRef,OrigAlt
```

[input_to_vep_head.txt](https://github.com/mskcc/vcf2maf/files/649813/input_to_vep_head.txt)

**Comment by ckandoth** [comment]
I modified your command slightly for consistency, but it should otherwise be the same. I am unable to reproduce the problem. Here are the relevant columns in the output MAF:
```bash
$ cut -f124- input_to_vep_head.vep.maf | head
#version 2.4
SAMPLE	OrigChrom	OrigStart	OrigRef	OrigAlt
WG698509-N	10	104264107	C	T
WG698509-N	10	104387019	T	C
WG698509-N	10	43610119	G	A
WG698509-N	10	70332580	A	G
WG698509-N	10	70405855	A	G
WG698509-N	10	88635779	C	A
WG698509-N	10	88683122	T	C
WG698509-N	11	108143456	C	G
```
If you're on the luna cluster, the following command is (nearly) equivalent to using the `cmo_vcf2maf` wrapper:
```bash
/opt/common/CentOS_6-dev/perl/perl-5.22.0/bin/perl /opt/common/CentOS_6-dev/vcf2maf/v1.6.12/vcf2maf.pl --input-vcf input_to_vep_head.txt --output-maf input_to_vep_head.vep.maf --custom-enst /opt/common/CentOS_6-dev/vcf2maf/v1.6.12/data/isoform_overrides_at_mskcc --vep-path /opt/common/CentOS_6-dev/vep/v86 --vep-data /opt/common/CentOS_6-dev/vep/v86 --vep-forks 4 --ref-fasta /opt/common/CentOS_6-dev/vep/v86/homo_sapiens/86_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --filter-vcf /opt/common/CentOS_6-dev/vep/v86/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz --max-filter-ac 10 --retain-info SAMPLE,OrigChrom,OrigStart,OrigRef,OrigAlt
```

**Comment by ckandoth** [comment]
@srinipr4 Let me know if this is working now. Also note that VEP on GRCh38 should provide better ClinVar annotations. I don't think they have updated the GRCh37 cache in a while. The easiest way to take advantage of GRCh38 annotation is to add this argument to vcf2maf: `--remap-chain /opt/common/CentOS_6-dev/vcf2maf/v1.6.12/data/GRCh37_to_GRCh38.chain`

**Comment by srinipr4** [comment]
@ckandoth : this works now! not sure what was the problem before. Thanks!
