### ISSUE TITLE
vcf2maf cannot handle large VCF files

### ISSUE THREAD

**Issue by mariecuriosity** [mskcc/vcf2maf#105]
I tried annotating the vcf file with 194947 variants:
`perl vcf2maf.pl --input-vcf input.vcf --output-maf output.maf`
and received the following error:
`Can't exec "/bin/sh": Argument list too long at vcf2maf.pl line 314.
Use of uninitialized value in concatenation (.) or string at vcf2maf.pl line 314.`
as well as another error (not sure if it's related) at multiple locations:
`WARNING: Couldn't retrieve bps around 1:14907 from reference FASTA: Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz`
It should be noted that I'm using samtools and bcftools version 1.3.1 and have the most up-to-date version of vcf2maf.

**Comment by ckandoth** [comment]
Thanks for reporting. As of 8560b97 from Sept, vcf2maf splits large VCFs internally into 100k chunks before running `samtools faidx`. So a possibility is that your OS supports fewer than 100k command-line arguments. Which OS are you using? You can run `getconf ARG_MAX` to check the argument limit. But based on my experience, it's a rough estimate.

**Comment by mariecuriosity** [comment]
I'm using a SLURM cluster, so I'm not entirely sure the properties of the exact node, but on the interactive node, getconf ARG_MAX = 4611686018427387903 and the OS is Linux n2194 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ckandoth** [comment]
Can you do me a massive favor and edit the chunk size `100000` in vcf2maf lines [313](https://github.com/mskcc/vcf2maf/blob/master/vcf2maf.pl#L313) and [336](https://github.com/mskcc/vcf2maf/blob/master/vcf2maf.pl#L336), until it works on one of your nodes? To start, see if it works with `10000`, to make sure that this is the problem. If it works fine with `10000`, then iteratively increase it so you can find the largest chunk size that works for you. Then I can use that as the default in the next stable release.

**Comment by mariecuriosity** [comment]
I edited it and it works wonderfully! It does take significantly longer to run, but now I can submit it as a batch job. Thanks!

**Comment by ckandoth** [comment]
Great. Glad to hear. What was the chunk size that worked for you? I would like to set it to something that works for most people.

**Comment by ckandoth** [comment]
In 68ad156 I reduced the 100k chunk size to 50k. Hopefully this supports your OS, and others with similar command-line argument limits. Closing thread.

**Comment by anishbhaswanth** [comment]
Hi,

I'm getting a similar error as well.

Here is the code I used:
```
    vcf2maf.pl --input-vcf $somatic_vcfs/${file_base%.vcf.gz}.somatic.vcf\
                --output-maf $maf_out/${sample}.maf \
                --tumor-id $tumor_id \
                --normal-id $normal_id \
                --species homo_sapiens \
                --ncbi-build GRCh38 \
                --cache-version 96 \
                --ref-fasta $ref \
                --vep-forks 14 \
                --vep-path $vep_path \
                --vep-data $vep_data
```
The error I get:
`Can't exec "/bin/sh": Argument list too long at /home/achakka/.conda/envs/variant_calling/bin/vcf2maf.pl line 376.`
`Use of uninitialized value in concatenation (.) or string at /home/achakka/.conda/envs/variant_calling/bin/vcf2maf.pl line 376.`

Any suggestions for this?
