### ISSUE TITLE
Make the VEP flag '--check_alleles' user selectable

### ISSUE THREAD

**Issue by cband** [mskcc/vcf2maf#106]
Thanks!

**Comment by ckandoth** [comment]
This is now implemented in f8b250e. Added the `--any-allele` flag which is disabled by default i.e. by default, VEP will have `--check_allele` enabled, and the user may choose to disable it by specifying the `--any-allele` flag. On the luna cluster you can access this using `cmo_maf2maf --version develop --help`, but you'd need to specify a non-zero value like `--any-allele 1` of the wrapper to work.
