### ISSUE TITLE
memory usage issues

### ISSUE THREAD

**Issue by rdmorin** [mskcc/vcf2maf#108]
I am having issues running vcf2maf on some systems due to the large memory footprint of VEP. This has been reported by others along with a known fix (https://www.biostars.org/p/176911/). I'm wondering if vcf2maf could be tweaked to allow the user to set the buffer size to be smaller than the default used by VEP so that memory is not an issue.

Thanks

**Comment by ckandoth** [comment]
Good idea. I'll add a `--buffer-size` argument to vcf2maf/maf2maf that will default to 5000, and pass it into the VEP command.

**Comment by ckandoth** [comment]
This is now implemented in f8b250e. You may use the code in the `master` branch for now. It may be a few weeks till I release a versioned release.

**Comment by rdmorin** [comment]
Great. Thank you.RyanOn Feb 3, 2017, at 6:26 AM, Cyriac Kandoth <notifications@github.com> wrote:This is now implemented in f8b250e. You may use the code in the master branch for now. It may be a few weeks till I release a versioned release.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mskcc/vcf2maf","title":"mskcc/vcf2maf","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/mskcc/vcf2maf" class="">https://github.com/mskcc/vcf2maf</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ckandoth in #108: This is now implemented in f8b250e. You may use the code in the `master` branch for now. It may be a few weeks till I release a versioned release."}],"action":{"name":"View Issue","url":"<a href="https://github.com/mskcc/vcf2maf/issues/108#issuecomment-277073205" class="">https://github.com/mskcc/vcf2maf/issues/108#issuecomment-277073205</a>"}}}
