### ISSUE TITLE
Uniprot isoform overrides

### ISSUE THREAD

**Issue by kmhernan** [mskcc/vcf2maf#109]
Hello,

Just trying to understand how this file was created? I'm trying to reproduce it, but failing. Any input?

**Comment by ckandoth** [comment]
@jjgao How was this was originally created?

**Comment by jjgao** [comment]
I had some code here to extract the mapping: https://github.com/jjgao/UniProtPyUtils/blob/master/src/uniprotisoformmapping.py

I think I cleaned up some redundant entries (one gene mapped to multiple isoforms) manually after that.

**Comment by ckandoth** [comment]
Thanks @jjgao. @kmhernan, I also made manual edits, to update HUGO symbols, and to add a gene that wasn't in there. A history of edits can be found here - https://github.com/mskcc/vcf2maf/commits/master/data/isoform_overrides_uniprot

**Comment by kmhernan** [comment]
Thank you guys. Ill look at the scripts and see if I have any issues.

**Comment by kmhernan** [comment]
@jjgao and @ckandoth I appreciate you guys helping me out. I am wondering if (when time permits) you could document this in the repository? I don't think I am alone in wanted to know this. I hope i'm not alone in being concerned about reproducible research ;-)

**Comment by ckandoth** [comment]
Sounds good. I'll leave this ticket open, and get it done before the next release. Thx Kyle.

**Comment by ckandoth** [comment]
I spent some time reviewing how `isoform_overrides_uniprot` was created, and there were few undocumented manual steps after [this script](https://github.com/jjgao/UniProtPyUtils/blob/master/src/uniprotisoformmapping.py). As JJ mentioned, there was some manual removal of redundant entries. And then later, some gap filling and updates like for `H3F3A` and `H3F3B` in [this commit](https://github.com/mskcc/vcf2maf/commit/1292ba5c987370e5b5396bcc93e4f41e30b47ddf). It will not be easy to create a document for this, but I will promise to create a gist where I attempt to reproduce @jjgao's  work. It won't exactly match his work, but it will have versioning and provenance. That will have to wait till October.
