### ISSUE TITLE
Maf2maf fails when input uses \r for new lines.

### ISSUE THREAD

**Issue by walidchatila** [mskcc/vcf2maf#112]
Happens in files created in Mac OS 9 or older, where only CR is used as the line break instead of LF (Unix) or CRLF (Windows).

**Comment by ckandoth** [comment]
Added checks in c7e8a9a for if the input uses CR as line breaks, and it will fail with an error, instead of trying to handle it. There are too many unix commands like `grep` used across these scripts, which don't play nice with files that use only CR as a line break.
