### ISSUE TITLE
ENSG00000163041 maps to both H3F3A and H3F3B

### ISSUE THREAD

**Issue by PichaiRaman** [mskcc/vcf2maf#113]
In the file (https://github.com/mskcc/vcf2maf/blob/master/data/ensg_to_entrez_id_map_ensembl_feb2014.tsv) the ensembl id ENSG00000163041 maps to 3021 (H3F3A) and 3020 (H3F3B). We noticed this because we expected to see a lot of H3F3A in a study we loaded but ended up with H3F3B mutations. The real H3F3B gene should map to ENSG00000132475 I believe.

ps - I think the reason your file lists both genes as mapping to ENSG00000163041 is that ensembl lists H3F3B as a synonym for H3F3A which may be some sort of legacy thing but its confusing since there is a real gene H3F3B (on a completely different chromosome).

**Comment by jjgao** [comment]
somehow h3f3a on uniprot links to h3f3b ensembl isoform (ENST00000254810): http://www.uniprot.org/uniprot/P84243

That's why the uniprot override is wrong for h3f3a

We don't have a uniprot override for h3f3b.

We need to fix it manually.
