### ISSUE TITLE
maf2vcf not parsing out allele depths

### ISSUE THREAD

**Issue by arnavaz** [mskcc/vcf2maf#117]
Hi!

I am running the maf2vcf perl script and I get an output vcf. However, the AD:DP values are empty in my file. 
In the command line I set the column names for --tum-rad-col and --tum-vad-col form my maf file column name for these values. But still they are not reflected in the vcf.

Can I ask why this happens?

Thank you!
Arna

**Comment by ckandoth** [comment]
Can you share the command you used, and a line or two from your input MAF?

**Comment by arnavaz** [comment]
Thank you very much! But I already figured out the problem!

Thanks again!

Arnavaz

**Comment by ckandoth** [comment]
Hi Arna. Is it a problem with maf2vcf that I can fix, so that other users can benefit from it? Or was it a problem with usage syntax?

**Comment by arnavaz** [comment]
I looked at the code and realized that I need to have the 'tumor_sample_barcode' column in my maf maf file. I added that and it worked.

Thanks!
Arna

**Comment by ckandoth** [comment]
Thanks Arna. That's useful feedback. I have placed [a sample MAF at this link](https://github.com/mskcc/vcf2maf/blob/master/data/minimalist_test_maf.tsv) with the minimal columns needed for maf2maf or maf2vcf to work right. Cheers!

**Comment by arnavaz** [comment]
Awesome!

Thanks for your support!

Arna
