### ISSUE TITLE
ERROR samtools

### ISSUE THREAD

**Issue by bastien-nguyen** [mskcc/vcf2maf#121]
Hi I  have installed samtools but I keep have this ERROR message:
perl vcf2maf.pl man
ERROR: Please install samtools, and make sure it's in your PATH

**Comment by ckandoth** [comment]
After installing samtools, did you make sure it's in your PATH?

**Comment by ckandoth** [comment]
You can use the command `which samtools` to confirm that samtools has been properly installed and is accessible in your terminal session.

**Comment by ckandoth** [comment]
Gonna close this issue, didn't hear back from OP.
