### ISSUE TITLE
The mpileup in vcf2vcf doesn't see indels in MSK-aligned BAMs

### ISSUE THREAD

**Issue by ckandoth** [mskcc/vcf2maf#122]
The command in [this line](https://github.com/mskcc/vcf2maf/blob/master/vcf2vcf.pl#L26) seems to call indels fine on BAMs downloaded from GDC like this one we have: `/ifs/tcga/gdc/files/47ac9742-74bc-4d76-a2ac-46c708e9cbbd/e30ade9704fbc29ccd9e6b69c91db237_gdc_realn.bam`

However, for MSK-IMPACT BAMs, and potentially all BAMs generated at MSK, indels are not called by mpileup. So there's something weird in the BAM format that needs to be handled differently. Here's a sample command that should generate some indels: `samtools mpileup --region MT --count-orphans --no-BAQ --min-MQ 1 --min-BQ 20 --ignore-RG --excl-flags UNMAP,SECONDARY,QCFAIL,DUP --BCF --output-tags DP,AD,ADF,ADR --ext-prob 20 --gap-frac 0.002 --tandem-qual 80 --min-ireads 1 --open-prob 30 --platforms illumina --fasta-ref /ifs/depot/resources/dmp/data/pubdata/hg-fasta/VERSIONS/hg19/Homo_sapiens_assembly19.fasta /ifs/res/share/taylorb/solitd/Proj_06604_D/r_001/alignments/Proj_06604_D_indelRealigned_recal_s_VS_egc_004_P.bam | bcftools view --type indels`

**Comment by rhshah** [comment]
Just FYI, https://github.com/rhshah/IMPACT-Pipeline/blob/master/bin/dmp_genotype_allele.pl#L431
This is how the counts are generated for MSK-IMPACT

**Comment by ckandoth** [comment]
The argument `--platforms` allows us to set a platform-specific indel error probability, and vcf2vcf sets this to `illumina`, which seems to prevent indels from being called in IMPACT BAMs. I'm not sure what exactly is happening under the hood, but it is reasonable to disable this feature, by using the default argument `--platforms all`. This is now fixed in 46c632c.
