### ISSUE TITLE
How to skip the VCF filtering step?

### ISSUE THREAD

**Issue by silvia-s** [mskcc/vcf2maf#126]
Hi Cyriac,

Even when I don't provide any vcf file, the script "vcf2maf.pl" still looks for the file "~/.vep/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz" (as default), which I don't have and don't want to use, since I would like to retain all my variants from the VCF file. Is there a way to skip the VCF filtering step altogether? 

Thanks for your help,
Silvia

**Comment by ckandoth** [comment]
Hi Silvia. No variants are removed by the filtering step. They are only tagged as "common_variant" under a column named `FILTER`. Please see the documentation for the `FILTER` column at https://github.com/mskcc/vcf2maf/blob/master/docs/vep_maf_readme.txt#L125

**Comment by ckandoth** [comment]
I'll leave this issue open, since it may be useful to people who don't want to add the "common_variant" tag.

**Comment by sbamin** [comment]
Nice if vcf filter option can be made optional, especially for genomes of other species.

```sh
vcf2maf.pl --input-vcf variants_filt_vcftools.snpeff.sorted.vcf --output-maf variants_filt_vcftools.snpeff.sorted.vc2maf.maf --ref-fasta CanFam3_1.fa --sp
ecies canis_familiaris
ERROR: Provided --filter-vcf is missing or empty: /~/.vep/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz
```

**Comment by ckandoth** [comment]
As of commit 3bbee40
@silvia-s `--filter-vcf` can now be set to `0` or `""` to disable `common_variant` tags under the FILTER column.
@sbamin vcf2maf ignores `--filter-vcf` when `--ncbi-build ne "GRCh37"`. However, your command doesn't specify `--ncbi-build` so it remains at the default value of `GRCh37`. As a fix, vcf2maf will also now require `--species eq "homo_sapiens"` before using the default `filter-vcf`.
