### ISSUE TITLE
variant_effect_predictor name changed 

### ISSUE THREAD

**Issue by pkhoueiry** [mskcc/vcf2maf#128]
"variant_effect_predictor.pl" is now named "vep" and vcf2maf is throwing an error.

vcf2maf.pl and or other scripts should be updated accordingly.

**Comment by ckandoth** [comment]
Hi. Each version of vcf2maf is tested alongside a specific version of Ensembl's VEP. The latest vcf2maf v1.6.13 is tested to work with VEP v86. As explained in the vcf2maf documentation, [this gist](https://gist.github.com/ckandoth/f265ea7c59a880e28b1e533a6e935697) explains how to install VEP v86, where the script is named `variant_effect_predictor.pl`. The renaming of the script to `vep` happened in Ensembl release v88, which may be supported by a future release of vcf2maf. For now, please use vcf2maf with VEP v86.
