### ISSUE TITLE
several arguments passed to vep are now deprecated

### ISSUE THREAD

**Issue by pkhoueiry** [mskcc/vcf2maf#129]
vcf2maf.pl is throwing errors because several arguments passed to "vep" are now deprecated. 
This includes: "--check_allele", "--gmaf" "--maf_1kg" and "--maf_es"

**Comment by ckandoth** [comment]
Please use vcf2maf with VEP v86. Support for VEP v88 and newer is planned, but it may be ~2 months till I get time to look at that. If you happen to look at it earlier, feel free to submit a pull request. Thanks much.
