### ISSUE TITLE
Integrating multiple vcf file into one MAF

### ISSUE THREAD

**Issue by leiendeckerlu** [mskcc/vcf2maf#130]
Hi there,

I was wondering if it is possible to integrate multiple vcf files of different samples into one large MAF file? For downstream analysis with tools such as maftools this would be highly useful!

Thank you!

**Comment by ckandoth** [comment]
To stay on par with the original goals of MAF format, vcf2maf only supports VCFs with a single sample or a tumor-normal pair. If you have a multi-sample VCF, they can be split with vcftools as described in [this post](https://www.biostars.org/p/108112/#108816). If you generate multiple MAFs from VCFs of different samples, they can be concatenated using something like this:
```bash
grep -h ^Hugo *.maf | head -n1 > merged.maf
grep -hEv "^#|^Hugo" *.maf >> merged.maf
```
