### ISSUE TITLE
MSK overrides file header is different from UniProt overrides header

### ISSUE THREAD

**Issue by angelicaochoa** [mskcc/vcf2maf#133]
These should match. The Genome Nexus server expects the file header seen in the UniProt overrides file but since the header is different, GN isn't able to parse the overrides data for MSK correctly, causing the annotator to use the wrong transcript ids in many cases.

**Comment by ckandoth** [comment]
Thanks. The header is just a comment line, not meant to be parsed. But you're right. To keep it consistent, in commit 7e6e4ed, I matched what you did for GN.

**Important note**: vcf2maf simply loads all the ENST transcript IDs into a hashmap, for use as overrides. So it gobbles up everything in column 1 and ignores everything else, including the gene names. This allows the use of more than one isoform override per gene. The only gene where this flexibility is useful is `CDKN2A`, which has two isoforms relevant in cancer. vcf2maf will pick the one that is affected more severely, based on [this ranking](https://github.com/mskcc/vcf2maf/blob/v1.6.14/vcf2maf.pl#L35). In Genome Nexus, I would recommend implementing the same kind of flexibility. Removing the dependence on `gene_name` also avoids the need to handle gene aliases or outdated HUGO symbols.
