### ISSUE TITLE
VEP 88/89 support

### ISSUE THREAD

**Issue by knightjimr** [mskcc/vcf2maf#134]
With version 88 of VEP, they changed the codebase and some of the options, and vcf2maf.pl does not work with those versions of VEP.  I was able to get it to work by doing the following:

   * Change the hard coded executable from "variant_effect_predictor.pl" to "vep"
   * Change the options --gmaf to --af, --maf_1kg to --af_1kg, --maf_esp to --af_esp
   * Remove deprecated option --check_allele, which is now done by default
   * Change the ann_cols columns for the MAF to AF, to match the new VEP annotations

But, I'm not sure that I did not miss something in the change.  Could you update the tool to support the new version of VEP?

**Comment by ckandoth** [comment]
Thanks for this. It's in my backlog. But unsure of when I can find the time. Probably on a weekend in Sept.

**Comment by zhujack** [comment]
Hi, vcf2maf does not work with VEP after VEP version 88, including 88, 89, 90, 91.  When you get a chance, could you update  "variant_effect_predictor.pl" to "vep"?  Thank you so much.

Jack

**Comment by ckandoth** [comment]
@knightjimr @zhujack This is now handled in commit d4027be which will make it into release `v1.6.16` shortly.
