### ISSUE TITLE
Multisample VCF: Samples names with 1 line per sample?

### ISSUE THREAD

**Issue by nroak** [mskcc/vcf2maf#136]
Is it possible to get a MAF file from a multisample VCF where only the samples containing alternate alleles for each variant are output in the MAF file?

**Comment by ckandoth** [comment]
Please use vcftools as described in this post - https://www.biostars.org/p/108112/#108816

**Comment by nroak** [comment]
This is very helpful. Thank you so much. I will check it out now.
