### ISSUE TITLE
ref_fasta gzip-ed with samtools faidx

### ISSUE THREAD

**Issue by alezanalp** [mskcc/vcf2maf#137]
In usage manual you have an example of reference FASTA file and it is gziped. But samtools can't index gzip-ed files (https://github.com/samtools/samtools/issues/237).

> --ref-fasta      Reference FASTA file [~/.vep/homo_sapiens/86_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz]

So when I've used custom gzip-ed reference file it fails with the error

**Comment by lordzappo** [comment]
You need to use bgzip, not gzip. 

http://manpages.ubuntu.com/manpages/wily/man1/bgzip.1.html
