### ISSUE TITLE
Dockerfile: Link to LOFTEE is broken

### ISSUE THREAD

**Issue by Selonka** [mskcc/vcf2maf#139]
Hi,

the link in the docker file for LOFTEE is broken.

Greetings Selonka

**Comment by ckandoth** [comment]
Hi Selonka. This repo does not use docker files, nor LOFTEE. What are you trying to solve?

**Comment by Selonka** [comment]
hi ckandoth,

I mean this file: https://github.com/mskcc/vcf2maf/blob/master/Dockerfile which install VEP and then load the content of the repo into the Docker container.  Or did I get something wrong? 

Greetings Selonka

**Comment by ckandoth** [comment]
Thanks! I forgot that existed. :) @mattions had put that in there. The broken link is now fixed in 6a0a4f7. I have a longer term issue https://github.com/mskcc/vcf2maf/issues/70 still pending, where I need to review and simplify that Dockerfile.
