### ISSUE TITLE
VCF Version change

### ISSUE THREAD

**Issue by nroak** [mskcc/vcf2maf#140]
When I run vcf2maf.pl, I get a warning,
`The version "4.2" not supported, assuming VCFv4.1`

The script seems to run fine, I just wanted to ensure that this is not a problem.
Also, given the different coordinate systems between VCF/MAF/Ensemble formats, are these accounted for in the resulting MAF file?

**Comment by ckandoth** [comment]
That [error message](https://github.com/vcftools/vcftools/issues/72) is often reported by `vcftools` on certain VCFs. But I don't use `vcftools` anywhere in vcf2maf. Are you sure this warning is from vcf2maf?

**Comment by ckandoth** [comment]
And yes, translating VCF's POS/REF/ALT/etc. into their equivalents in MAF format, are all coded into vcf2maf.

**Comment by nroak** [comment]
Yes, of course! Thanks for that and apologies for missing that. I was running the steps enlisted here, https://www.biostars.org/p/108112/#108816, for using vcf2maf on a multi-sample vcf. The warning is thrown in an earlier step using vcf-subset.
Also, thanks for the clarification on the co-ordinates.

**Comment by ckandoth** [comment]
No worries. I'm sure the warning from vcftools is benign, but worth googling around for.
