### ISSUE TITLE
Include ability to re-liftover back to hg19

### ISSUE THREAD

**Issue by dannykwells** [mskcc/vcf2maf#141]
We love using vcf2maf! One (small) feature request would be (for those of us using hg19) the ability to map *back* to hg19 after the vcf2maf is done, so that our maf would be compatible with our vcfs and any other analyses we are doing. Right now we are having to do that by hand, and it's not a huge deal but this would add convenience and make things more seamless.

**Comment by dannykwells** [comment]
Ok, we just went ahead and did this with a small python script. If there any interest fine submitting a PR.

**Comment by ckandoth** [comment]
Thanks Danny. Sorry, I forgot to respond. VEP will work with input VCFs that use hg19 chrom-names, although I'm not sure how/if they handle the older `chrM` sequence in hg19. If your input to vcf2maf is an hg19 VCF, then use it as is. Use the hg19 reference fasta in `--ref-fasta`, and don't use `--remap-chain hg19_to_GRCh37`, which I'm assuming you did. Lemme know. I'll leave this issue open.

**Comment by ckandoth** [comment]
When using `remap-chain`, vcf2maf will now add a column named `REMAPPED_POS` which retains the original `CHROM:POS:REF:ALT` from the input VCF. Implemented in 42d0548.
