### ISSUE TITLE
maf2maf for liftover?

### ISSUE THREAD

**Issue by nroak** [mskcc/vcf2maf#144]
I am working with the TCGA masked somatic mafplus files. But I realized that all of these files are in GRCh38 assembly. I was wondering if I can use maf2maf script to lift them over to GRCh37 assembly. I see no other way of doing a liftover of a MAF file. Suggestions are welcome.

**Comment by Marmach** [comment]
+1
I'm actually interested in a very similar thing (specifically I need to reformat TCGA MAFs into hg19 VCFs), but I actually got stuck trying to use MAF2VCF or MAF2MAF on a MAF downloaded from GDC and no matter how I try, I get:
> ERROR: Make sure that ref-fasta is the same genome build as your MAF:

(even when adding path to hg38 reference fasta, no matter if zipped or unzipped).

**Comment by MHBailey** [comment]
I'm looking to do the same thing. Just curious if there was any movement on this?

**Comment by ckandoth** [comment]
@nroak @MHBailey I have no plans to implement the `--remap-chain` feature into maf2maf. It would need a refactor. However, the `--remap-chain` feature is available in vcf2maf and vcf2vcf.

@Marmach you can use maf2vcf to turn your MAF into a VCF, and then vcf2vcf with `--remap-chain data/GRCh38_to_GRCh37.chain`. The error is saying that your chromosome names in the MAF do not match the chromosome names in your `--ref-fasta`. If you can't figure that out, then open a new issue with example data, and I'll try to help debug.
