### ISSUE TITLE
N's in cDNA annotation

### ISSUE THREAD

**Issue by NitaH0321** [mskcc/vcf2maf#146]
Hi, I am trying to better understand what might be going wrong when using the --ref-fasta option to supply my own reference that matches the bam files I received. These have "chr" in the chromosome name and I did not think that would affect much. All other annotations are fine, and there are no errors that point to why only the cDNA annotation always has N's. (i.e.  c.110N>A rather than c.110G>A) Testing using the maf2maf script without "chr" on the same data by just modifying the input maf strongly indicates that this is the issue. Is there something I am not aware of that I am supposed to change?

**Comment by ckandoth** [comment]
Ensembl VEP does not officially support chr-prefixes in chromosome names. However, it will safely handle it for human GRCh37 and GRCh38. I have seen some oddities with it annotating indels as "coding_region_variant", but I'm not entirely sure it's related to the chr-prefix. In general, your input MAF/VCF and the reference FASTA should have matching chromosome names. Can you tell me which reference your BAMs were aligned to? And a sample input line?

**Comment by ckandoth** [comment]
No response from OP. Closing issue.
