### ISSUE TITLE
Vep v90 and GnomAD

### ISSUE THREAD

**Issue by apastore** [mskcc/vcf2maf#148]
Hi Cyriac,
I have seen you aim for a new release with Vep v90 soon. 
Just asking if you will aim to add support for the GnomAD or keep ExAC?

Thanks!
Alessandro

**Comment by ckandoth** [comment]
Hi Alessandro I aim to replace ExAC with GnomAD in the next release. However, I don't have an estimate on when I can work on the next release.

**Comment by ckandoth** [comment]
Commit d47eee7 adds support for the newer VEP v91, and adds columns for gnomAD allele freqs. It is not yet used for filtering. gnomAD still needs to be whitelisted for known somatic mutations, like I did for the ExAC_nonTCGA subset.
