### ISSUE TITLE
EBI VCF validator compatibility

### ISSUE THREAD

**Issue by walidchatila** [mskcc/vcf2maf#150]
maf2vcf output changes:

- [x] add header lines describing each of the GRCh37 chromosomes+contigs
- [x] add a reference header
- [x] For the following header, change "Number=G" to "Number=R"
```
##FORMAT=<ID=AD,Number=G,Type=Integer,Description="Allelic depths of REF and ALT(s) in the order listed">
```
- [ ] the VCF needs to be sorted

**Comment by ckandoth** [comment]
Thanks Walid. This is done in commit 1024307 and will make it into release v1.6.16 shortly. I am not implementing vcf sorting, since that can be done downstream by bcftools and vcf-sort.
