### ISSUE TITLE
Handle edge case event that should be a stop_lost

### ISSUE THREAD

**Issue by ckandoth** [mskcc/vcf2maf#156]
```
##fileformat=VCFv4.2
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
3       178952147       .       AACTGAAAAGAT    A       .       .       .
```
It is currently being reported by the offline VEP as `coding_sequence_variant`, while the [REST API](https://grch37.rest.ensembl.org/vep/human/hgvs/3:g.178952148_178952158delACTGAAAAGAT?content-type=application/json&hgvs=1) correctly reports `stop_lost`.

**Comment by angelicaochoa** [comment]
@ckandoth I heard back from Ensembl and learned that it is a software update issue. Waiting to hear back to confirm whether our cache/databases need to be updated as well for the new software version.

From Ensembl:

> The issue is arising due to an update that has happened since the version 89
was released. We updated the code to enable better prediction of calling
deletions over the end of CDS. You can see the any updates here:
https://github.com/Ensembl/ensembl-variation/commits/release/91/modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm

>Any complex changes are referred to as 'coding sequence variant', so until this
update occurred stop lost consequences were included under that umbrella term.

**Comment by ckandoth** [comment]
Commit d4027be adds support for the newer VEP (v89 and higher), while retaining backward compatibility with older versions. I'll handle a few other unrelated issues, and release this into vcf2maf v1.6.16, which will default to using VEP v91.
