### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by kb472** [mskcc/vcf2maf#159]
I'm getting a warning: No genotype column for T_001 in vcf file. 

I input a vcf which has a column with genotype. Not sure why its giving this warning

It did output a maf file - can I go ahead and use this maf file ?

**Comment by ckandoth** [comment]
This warning occurs when there is "No genotype column for T_001 in vcf file". Can you give me the header line of the VCF (starts with `#CHROM`) and also the actual command you used. Thanks.

**Comment by kb472** [comment]
Tried this again and the issue is now not occurring. So closing this issue
