### ISSUE TITLE
vcf2Maf without VEP

### ISSUE THREAD

**Issue by karthigayini** [mskcc/vcf2maf#160]
I have snpEFF annotated VCFs which needs to be converted to MAF. Is there a way to do this with your tool without installing VEP?

**Comment by ckandoth** [comment]
Recent versions of snpEff generate VCFs with annotations under `INFO/ANN` which is compliant with VEP annotations. `vcf2maf` seeks either `INFO/CSQ` or `INFO/ANN` and extracts data from it. If your `--input-vcf` is named `test.vcf`, then make a copy beside it named `test.vep.vcf`, and then vcf2maf will skip reannotation with VEP and attempt to extract information from the `INFO/ANN` field.

**Comment by YuvaraniThambidurai** [comment]
Hi
   I have a VCF file generated from Mutect2, Is there any tool available to convert it into MAF file without using VEP. Thanks in advance.

Regards,
Yuvarani

**Comment by MatthewP-Newbee** [comment]
Hello, this method has some problem? I annotate with snpEff then copy to `*.vep.vcf`, but the maf file `Hugo_Symbol` field is all **Unknown**. Does this relative to my annotation? Here I show one of the ANN record:
> ANN=C|disruptive_inframe_deletion|MODERATE|PLEKHN1|ENSG00000187583|transcript|ENST00000379409|protein_coding|1/15|c.53_55delTCT|p.Phe18del|83/2455|53/1992|18/663||INFO_REALIGN_3_PRIME,C|disruptive_inframe_deletion|MODERATE|PLEKHN1|ENSG00000187583|transcript|ENST00000379410|protein_coding|1/16|c.53_55delTCT|p.Phe18del|88/2404|53/1836|18/611||INFO_REALIGN_3_PRIME,C|disruptive_inframe_deletion|MODERATE|PLEKHN1|ENSG00000187583|transcript|ENST00000379407|protein_coding|1/15|c.53_55delTCT|p.Phe18del|83/2194|53/1731|18/576||INFO_REALIGN_3_PRIME,C|upstream_gene_variant|MODIFIER|PLEKHN1|ENSG00000187583|transcript|ENST00000480267|retained_intron||n.-4293_-4291delCTT|||||4293|,C|downstream_gene_variant|MODIFIER|KLHL17|ENSG00000187961|transcript|ENST00000338591|protein_coding||c.*1391_*1393delCTT|||||867|,C|downstream_gene_variant|MODIFIER|KLHL17|ENSG00000187961|transcript|ENST00000463212|retained_intron||n.*4104_*4106delCTT|||||4104|,C|downstream_gene_variant|MODIFIER|KLHL17|ENSG00000187961|transcript|ENST00000466300|nonsense_mediated_decay||c.*3196_*3198delCTT|||||2052|,C|downstream_gene_variant|MODIFIER|KLHL17|ENSG00000187961|transcript|ENST00000481067|retained_intron||n.*2418_*2420delCTT|||||2418|
>

**Comment by tiramisutes** [comment]
> Recent versions of snpEff generate VCFs with annotations under `INFO/ANN` which is compliant with VEP annotations. `vcf2maf` seeks either `INFO/CSQ` or `INFO/ANN` and extracts data from it. If your `--input-vcf` is named `test.vcf`, then make a copy beside it named `test.vep.vcf`, and then vcf2maf will skip reannotation with VEP and attempt to extract information from the `INFO/ANN` field.

Hello, I try this way, but still not working.

**Comment by FriederikeHanssen** [comment]
Hi! 

I also have a set of VCFs annotated with snpEff.

I merged them initially as described here: https://www.biostars.org/p/461842/

Running this with the following command: 

```
vcf2maf.pl --input-vcf merge.vep.vcf --output-maf Merged_snvs.maf --ref-fasta /path/to/Homo_sapiens_assembly38.fasta --filter-vcf 0 --ncbi-build GRCh38
```

I keep getting this error though: 

```
STATUS: Running VEP and writing to: ./merge.vep.vep.vcf
ERROR: Cannot find VEP script in path: /home-link/vep
```

VEP is available in the path.

**Comment by ckandoth** [comment]
@FriederikeHanssen vcf2maf is expecting VEP to be under `/home-link/vep`, not in your environment `$PATH`. You can tell vcf2maf where VEP lives using argument `--vep-path`. Technically, you don't need VEP because you already used snpEFF - in this case, be sure to use `--inhibit-vep` to avoid re-annotation. Please read about more command-line arguments using `perl vcf2maf.pl --man`.

**Comment by FriederikeHanssen** [comment]
@ckandoth Thank you for your help. I tried --vep-path initially. Then it didn't work. However, now it runs 👍 

I do get this WARNING now:

```
use of uninitialized value in list assignment
```

Same as described here: https://github.com/mskcc/vcf2maf/issues/174

Does that mean I can't run vcf2maf with snpEff afterall?

**Comment by ckandoth** [comment]
@FriederikeHanssen that's just a warning. See my update to the first comment above.

**Comment by FriederikeHanssen** [comment]
@ckandoth ok. It finally worked. However, when running MAFtools looks like everything in column Variant_Classification is annotated as IGR in the MAF. In the vcf I can see though that this is not the case. I read the manual, but I couldn't find whether there is a specific parameter I have to set. Any hints?

**Comment by ckandoth** [comment]
Please open a new issue @FriederikeHanssen
