### ISSUE TITLE
Should "panel_of_normal" be discarded for downstream analysis?

### ISSUE THREAD

**Issue by ShixiangWang** [mskcc/vcf2maf#163]
Hello @ckandoth,

I have a question when I use VEP predict the Variant Effect with VCF file which transformed by `maf2vcf.pl`. 

I find records like

```
chr1	152312907	.	G	C	.	panel_of_normals	.	GT:AD:DP
```

in the vcf file.

I cannot figure out the `panel_of_normals` means by google.   Should I rule out such rows by `vcftools` and only keep `PASS` rows before I use VEP?

Best wishes,
Shixiang

**Comment by ShixiangWang** [comment]
After using VEP, I wanna call pVACtools pipline <http://pvactools.readthedocs.io/en/latest/pvacseq/prerequisites.html#vep>, which needs a VEP annotated single-sample VCF.

Can I realize it by giving option `--per-tn-vcfs`  according to the usage of `maf2vcf.pl`. Or I should split origin maf into per sample maf and call `maf2vcf.pl` one by one?
```
$ ./maf2vcf.pl --man
NAME
     maf2vcf.pl - Reformat variants in a MAF into a multisample VCF with GT:AD:DP data if available

SYNOPSIS
     perl maf2vcf.pl --help
     perl maf2vcf.pl --input-maf test.maf --output-dir vcfs

OPTIONS
     --input-maf      Path to input file in MAF format
     --output-dir     Path to output directory where VCFs will be stored, one per TN-pair
     --output-vcf     Path to output multi-sample VCF containing all TN-pairs [<output-dir>/<input-maf-name>.vcf]
     --ref-fasta      Path to reference Fasta file [~/.vep/homo_sapiens/91_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz]
     --per-tn-vcfs    Specify this to generate VCFs per-TN pair, in addition to the multi-sample VCF

```

**Comment by ckandoth** [comment]
`panel_of_normals` is a tag copied from the FILTER column in the MAF you downloaded from GDC. The tag is described here - https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format

**Comment by ckandoth** [comment]
I found more information [in this PDF](https://docs.gdc.cancer.gov/Data/PDF/Data_UG.pdf):
```
The MuTect2 pipeline employs a “Panel of Normals” to identify additional germline mutations. This panel is generated using TCGA blood normal genomes from thousands of individuals that were curated and confidently assessed to be cancer-free. This method allows for a higher level of confidence to be assigned to somatic variants that were called by the MuTect2 pipeline.
```

**Comment by ShixiangWang** [comment]
Thank you. :)

发自我的 iPhone

在 2018年3月30日，下午11:14，Cyriac Kandoth <notifications@github.com<mailto:notifications@github.com>> 写道：


I found more information in this PDF<https://docs.gdc.cancer.gov/Data/PDF/Data_UG.pdf>:

The MuTect2 pipeline employs a “Panel of Normals” to identify additional germline mutations. This panel is generated using TCGA blood normal genomes from thousands of individuals that were curated and confidently assessed to be cancer-free. This method allows for a higher level of confidence to be assigned to somatic variants that were called by the MuTect2 pipeline.


―
