### ISSUE TITLE
Error while converting pancancer maf to vcf

### ISSUE THREAD

**Issue by banerjeeshayantan** [mskcc/vcf2maf#170]
I am trying for quite sometime to convert [https://www.synapse.org/#!Synapse:syn1461168](url) Lung cancer maf file to vcf. The command I am giving is : 
perl maf2vcf.pl --input-maf LUSC_Paper_v8.aggregated.tcga.whitelist.maf --ref-fasta hg19.fa --output-dir /media/sb/disk21/data
I am getting error 
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65272.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65273.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65274.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65275.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65276.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65277.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65278.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65279.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65280.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65281.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65282.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65283.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65284.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65285.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65286.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65287.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65288.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65289.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65290.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65291.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65292.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65293.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65294.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65295.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65296.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65297.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65298.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65299.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65300.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65301.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65302.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65303.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65304.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65305.
Use of uninitialized value $filter in split at maf2vcf.pl line 97, <GEN0> line 65306.
[W::fai_fetch] Reference 20:23345384-23345386 not found in FASTA file, returning empty sequence
Failed to fetch sequence in 20:23345384-23345386
[W::fai_fetch] Reference 1:68171222-68171224 not found in FASTA file, returning empty sequence
Failed to fetch sequence in 1:68171222-68171224
ERROR: Make sure that ref-fasta is the same genome build as your MAF: hg19.fa  
**I am pretty sure the build in my maf file is Grch37 and I have downloaded the corresponding hg19.fa file from UCSC database. I am unable to understand the rest. Kindly suggest something.**

**Comment by ckandoth** [comment]
`hg19` and `Grch37` are not the same thing. Please see https://www.biostars.org/p/119295/#119308
