### ISSUE TITLE
Keep allele frequencies in the output MAF

### ISSUE THREAD

**Issue by Tato14** [mskcc/vcf2maf#175]
Hi!
I'm newbie in this type of analysis. I am performing targeted panel data analysis without the normal tissue counterpart. After GATK analysis and some filtering I got some variants both germinal and somatic. I would like to kee both for further analysis but I am not sure if I could keep the AF in order to discern between them if I use VCF2MAF. 

Are the `t_depth`, `t_ref_count` and `t_alt_count` the arguments that I should look to recalculate the AF?

Thanks!

**Comment by ckandoth** [comment]
Yes, that's correct. vcf2maf does not care if your variants are somatic or germline. And a matched normal is optional. To comply with MAF format, it will use `NORMAL` as a placeholder normal sample ID. In downstream analysis, you can calculate Variant Allele Fraction (VAF) by doing `t_alt_count ÷ t_depth` assuming `t_depth` is non-zero. If there is any additional information in the VCF that you want in MAF format, see the documentation for the argument `--retain-info`.
