### ISSUE TITLE
Running vcf2maf on snpeff-annotated vcfs

### ISSUE THREAD

**Issue by rasiimwe** [mskcc/vcf2maf#181]
Hi,

I have vcf files that were annotated using snpeff v4.3 and I would like to convert them to maf using vcf2maf.

My first run included the VEP component (below) but I got odd results when I run MutsigCV using the maf file I had generated:

"perl vcf2maf.pl --input-vcf file.vcf --output-maf file.maf --ref-fasta ~/GRCh37-lite.fa --vep-forks 4 --vep-path ~/vep --ref-fasta $VEP_DATA/homo_sapiens/86_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --species homo_sapiens --tumor-id tid --normal-id nid"

I then tried another run (below) that skips the VEP annotation step (following #160 ) 

"perl vcf2maf.pl --input-vcf file.vcf --output-maf file.maf --ref-fasta ~/GRCh37-lite.fa --species homo_sapiens --tumor-id ddd --normal-id dddnn" 

I got the following errors:

Use of uninitialized value in list assignment at ~/vcf2maf.pl line 649, <gen4> line 2186.
Use of uninitialized value in list assignment at ~/vcf2maf.pl line 649, <gen4> line 2186.
Use of uninitialized value in list assignment at ~/vcf2maf.pl line 649, <gen4> line 2186.
Use of uninitialized value in list assignment at ~/vcf2maf.pl line 649, <gen4> line 2186.
Use of uninitialized value in list assignment at ~/vcf2maf.pl line 649, <gen4> line 2186.
...

Where could I be going wrong and how best can I go about this?
Thanks

**Comment by Spenca** [comment]
I have this issue as well.

**Comment by tsy19900929** [comment]
https://github.com/tsy19900929/snpeffToMaf

**Comment by ckandoth** [comment]
@rasiimwe those are warnings complaining that the snpEff VCF is missing fields that vcf2maf expects. vcf2maf is designed for VEP's `INFO/ANN` format, defined as follows in a VCF header:
```
##INFO=<ID=ANN,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|ALLELE_NUM|DISTANCE|STRAND|FLAGS|PICK|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|TSL|CCDS|ENSP|SWISSPROT|TREMBL|UNIPARC|RefSeq|GENE_PHENO|SIFT|PolyPhen|DOMAINS|HGVS_OFFSET|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|CLIN_SIG|SOMATIC|PHENO|PUBMED|MOTIF_NAME|MOTIF_POS|HIGH_INF_POS|MOTIF_SCORE_CHANGE|TRANSCRIPTION_FACTORS">
```

Whereas snpEff 5.0 `INFO/ANN` format looks like this:
```
##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO' ">
```
Fields are named differently, there is whitespace that needs cleanup, and their values are possibly different too. So it will take effort to make vcf2maf safely extract data from snpEff-annotated VCFs. I do not have the bandwidth for this. Feel free to submit a pull request. Otherwise, I strongly recommend using VEP with vcf2maf.
