### ISSUE TITLE
 # ::NOTE:: If seen in a DB other than dbSNP, this field will remain blank

### ISSUE THREAD

**Issue by Tato14** [mskcc/vcf2maf#185]
Hi,

I was trying to get variants appeared in COSMIC and I found this comment in the source code:

`# If VEP couldn't find this variant in dbSNP/COSMIC/etc., we'll say it's "novel"
            if( $effect{Existing_variation} ) {
                # ::NOTE:: If seen in a DB other than dbSNP, this field will remain blank
                $effect{dbSNP_RS} = join( ",", grep{m/^rs\d+$/} split( /,/, $effect{Existing_variation} ));
            }
            else {
                $effect{dbSNP_RS} = "novel";
}`

Which DB are the ones considered to let the `Existing_variation` blank?
Thanks!

**Comment by ckandoth** [comment]
`Existing_variation` is what VEP reports based on [these databases](http://useast.ensembl.org/info/genome/variation/species/sources_documentation.html) and will contain the COSMIC IDs you are looking for. The code you pasted edits the `dbSNP_RS` field to comply with MAF format.
