### ISSUE TITLE
Citing vcf2maf

### ISSUE THREAD

**Issue by brunogrande** [mskcc/vcf2maf#189]
Hey, @ckandoth! 

**Quick question:** Is there anything I can cite for using vcf2maf other than the VEP publication or a link to your GitHub? You deserve credit where credit is due.

**Comment by ckandoth** [comment]
Thanks very much @brunogrande. Choose the release version you used e.g. `v1.6.16` and cite it as:
`Cyriac Kandoth, vcf2maf v1.6.16 (2018), GitHub repository, https://github.com/mskcc/vcf2maf/releases/tag/v1.6.16`

**Comment by ckandoth** [comment]
I have tried [Zenodo](https://guides.github.com/activities/citable-code/) before as recommended by GitHub, and gave up in it, because it needed to be updated with every commit/release. Also their server [appears to be down today](https://twitter.com/ZENODO_ORG/status/1030485682068877314).
