### ISSUE TITLE
Add ability to use VEP's custom annotations feature

### ISSUE THREAD

**Issue by ckandoth** [mskcc/vcf2maf#19]
For example, if someone had a tabix-indexed ExAC VCF, they could append minor allele frequencies to the resulting MAF as follows:

    perl variant_effect_predictor.pl -i example_GRCh37.vcf -cache -custom ExAC.r0.3.sites.vep.vcf.gz,ExAC,vcf,exact,0,AF

**Comment by lordzappo** [comment]
Where can I find a copy of this exac vcf?  ftp://ftp.broadinstitute.org/pub/ExAC_release this site keeps timing out for me.

**Comment by ckandoth** [comment]
Use this one on Luna for now, but later it needs to be moved to a proper folder under /ifs/depot...

    /ifs/work/socci/Depot/Pipelines/Variant/PostProcess/db/ExAC.r0.3.sites.pass.minus_somatic.vcf.gz

**Comment by ckandoth** [comment]
This one's solved in v1.6.3.
