### ISSUE TITLE
Misannotated ONPs

### ISSUE THREAD

**Issue by kpjonsson** [mskcc/vcf2maf#190]
Long ONPs spanning coding regions get misannotated as missense mutations. These are likely false positive mutation calls, but the misannotation is still an issue.

See for example: `/ifs/res/taylorlab/jonssonp/test.maf`

**Comment by ckandoth** [comment]
Thanks I've noticed this, but ignored them cuz they were crap events. But it is technically missense because it's an inframe substitution. I can't think of another SO term that is appropriate. If they altered a splice junction them it should be annotated as `splice_` something.

**Comment by kpjonsson** [comment]
Hm, ok. Since they're crap either way I can circumvent them.

**Comment by ckandoth** [comment]
In the latest Roslin v2.4.0 we no longer report events uniquely called by Pindel. For now, they will remain in the VCFs and the unfiltered per-sample MAFs, but will be removed from the analysis/portal MAFs.

Per our validation against DMP's clinical sequencing results, Abra+VarDict recovers all signed out indels including really long ones like a 362bp FOXA1 deletion. We did not have a dataset to test recovery rate for FLT3 ITDs, but DMP confirmed that they will soon stop running Pindel in the clinical sequencing pipeline.

**Comment by kpjonsson** [comment]
That's a relief. Good to hear.
