### ISSUE TITLE
Questionable output when running vcf2maf

### ISSUE THREAD

**Issue by caaespin** [mskcc/vcf2maf#193]
Hi there, 

I'm trying to run vcf2maf but I'm getting two types of (I assume) errors:

```
Argument "." isn't numeric in array or hash lookup at vcf2maf.pl line 778, <GEN4> line 1000.
Argument "." isn't numeric in numeric gt (>) at vcf2maf.pl line 587, <GEN4> line 1001.
```

The VCF in question has a `GT` value of `./1` which, inspecting the code, causes the first error.  The second one is caused, I believed, by `AD` having a value of `.`. 

Is this output expected? Or is it an actual error I should investigate on my side? 

A maf is produced in the end, but I'm not sure if those error messages are something that should be of concern, or if they can be ignored. 

Thanks!

**Comment by ckandoth** [comment]
Thanks for reporting. The warnings are usually benign, and since you have identified that the input had "." in spots where they are uncommon, you can ignore them. Just be wary of empty fields in the final MAF.

**Comment by zuoyizhang** [comment]
Hello,

In my vcf file, gt values are not 0 or 1. They are charatcers, e.g., A, C, G, T. Do they affect the final MAF files?

Thanks!
