### ISSUE TITLE
vcf2maf for structure variation and GRCh38

### ISSUE THREAD

**Issue by lh12565** [mskcc/vcf2maf#198]
Hi, I wonder if vcf2maf can annotate VCF files of structure variation, such as translocations? 
And the reference genome that I used for mapping the reads and generating the VCF file was GRCh38. Can I use following command to convert  the VCF to MAF?

perl vcf2maf.pl --input-vcf t1-1.vcf --output-maf t1-1.maf --tumor-id P1T1 --normal-id P1N1 --ref-fasta GRCh38.fa.gz

Thanks!
Luo Hao

**Comment by ckandoth** [comment]
Hello. vcf2maf v1.6.15 added support for SV VCFs created by Delly. Theoretically, it should work for most SVs represented in VCF 4.1 or newer.
