### ISSUE TITLE
vcf2maf can't annotate big vcf files

### ISSUE THREAD

**Issue by SBata** [mskcc/vcf2maf#199]
hi there

I have a vcf file with 25k calls.

I came across the error (edit: I added the first two lines too)
```
Can't exec "/usr/local/bin/samtools": Argument list too long at Documents/vcf2maf-1.6.16/vcf2maf.pl line 367.
Use of uninitialized value in concatenation (.) or string at Documents/vcf2maf-1.6.16/vcf2maf.pl line 367.
WARNING: Couldn't retrieve bps around XX:yyyyyy from reference FASTA
```

I looked at the posts:
https://github.com/mskcc/vcf2maf/issues/94
and
https://github.com/mskcc/vcf2maf/issues/105

I have the latest version of vcf2maf obtained from github, latest version of samtools.
samtools is able to find the location around the bp missed by vcf2maf as suggested here:
https://github.com/mskcc/vcf2maf/issues/94#issuecomment-259158198

then, to test it, I scaled down my vcf file keeping
5,000
10,000
15,000
and at 15k is where I got the error, and I understand is because of `samtools faidx` block size

however, the previous posts indicate that this issue is resolved, but I still get this error....
any suggestions?

thanks

**Comment by kpjonsson** [comment]
That warning message suggests your VCF file contains coordinates (specifically position `yyyyyy` on chromosome `XX`) that do not exist in the reference FASTA file you are using. It's likely unrelated to the file size.

**Comment by SBata** [comment]
I'm sure that's the case.
for example, the first lines of the the error are:
```
Can't exec "/usr/local/bin/samtools": Argument list too long at Documents/vcf2maf-1.6.16/vcf2maf.pl line 367.
Use of uninitialized value in concatenation (.) or string at Documents/vcf2maf-1.6.16/vcf2maf.pl line 367.
WARNING: Couldn't retrieve bps around 1:744366 from reference FASTA: Canis_familiaris.CanFam3.1.dna.toplevel.fa

```
I then check in the CanFam reference file that I used:
```
samtools faidx Canis_familiaris.CanFam3.1.dna.toplevel.fa 1:744360-744372
>1:744360-744372
TCCCCATGGTGAA
```

which indicates that the "missed" position is actually in the reference file...

**Comment by ckandoth** [comment]
Most command-line interfaces (CLI) have a limit to the total length of a command and its arguments. At [this line of code](https://github.com/mskcc/vcf2maf/blob/v1.6.16/vcf2maf.pl#L366), I limit the number of arguments passed into `samtools faidx` to `50000`, which work fine on most Linux distributions, but I was recently made aware that `50000` is too high on Mac OSX. So I have reduced this to `5000` in `v1.6.16`. Please download `v1.6.16` again, and try.

**Comment by SBata** [comment]
thank you @ckandoth .

I directly edited that line of code on my computer in the `vcf2maf.pl` file to `5000` instead of `50000` and it did run smoothly with roughly 23k SNVs (from MuTect).

I also ran one from 40k SNVs from a Varscan2 file and it also seems to ran well (it's a big file so it's taking some time). the only warning(s) I got for that is the following in the step of VEP annotation (there are several of them all saying the same thing):
```
STATUS: Running VEP and writing to: VS_SNV.Somatic.vep.vcf
WARNING: 82150 : Odd number of elements in hash assignment at Documents/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 526.
```
is that something I should be worried about ? what causes it? should I post it on the VEP github?

**Comment by ckandoth** [comment]
Glad it worked. There is also a `50000` limit for a tabix command that I reduced in another part of the code. I recommend downloading `v1.6.16` again to take advantage of that.

Regd the `Odd number of elements` warning, that is coming from [this code in VEP](https://github.com/Ensembl/ensembl-vep/blob/release/94/modules/Bio/EnsEMBL/VEP/BaseVEP.pm#L522-L528), and likely an unhandled exception of VEP on `Canis_familiaris` reference FASTA. I would not worry about it, unless you find something unusual in your final results. Feel free to open another issue, for other issues.

**Comment by SBata** [comment]
great, thank you!
