### ISSUE TITLE
Variants not being annotated with HGVSp_Short

### ISSUE THREAD

**Issue by thomasyu888** [mskcc/vcf2maf#203]
For version 1.6.14, there are many variants not being annotated with an HGVSp_Short..  Is this a known bug?

What could be the cause of this?

**Comment by ckandoth** [comment]
This is not a known issue. Send a sample input and we can debug. I'm only familiar with this happening if the `--ref-fasta` genome does not match what you are trying to annotate. Check your input VCF/MAF for systematic bugs.

**Comment by thomasyu888** [comment]
Would you expect there to be no annotation if the Variant_classification is set as an Intron?

**Comment by ckandoth** [comment]
Yes, only mutations in protein coding exons will have a non-empty `HGVSp_Short`

**Comment by thomasyu888** [comment]
Thanks for the information!  Will re-open if necessary.
