### ISSUE TITLE
Not able to convert VCF to MAF

### ISSUE THREAD

**Issue by sunnykevin19** [mskcc/vcf2maf#205]
Hi, not able to figure out the error, were it went wrong ?
./vcf2maf.pl --input-vcf /mnt/data/PERG.bam_GATK.vcf --output-maf /mnt/data/PERG.maf --species loxodonta_africana --filter-vcf 0  --ref-fasta /mnt/ref/LoxArf4.fasta --vep-path /usr/local/softw/ensembl-vep --vep-data /mnt/VEP/loxodonta_africana_vep_94_loxAfr3.tar.gz 
STATUS: Running VEP and writing to: /mnt/data/PERG.bam_GATK.vep.vcf

-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /mnt/VEP/loxodonta_africana_vep_94_loxAfr3.tar.gz/loxodonta_africana not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311
STACK Bio::EnsEMBL::VEP::CacheDir::init /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /usr/local/softw/ensembl-vep/vep:224
Date (localtime)    = Fri Dec 21 13:05:21 2018
Ensembl API version = 94
---------------------------------------------------

ERROR: Failed to run the VEP annotator! Command: /usr/bin/perl /usr/local/softw/ensembl-vep/vep --species loxodonta_africana --assembly GRCh37 --offline --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --pubmed --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir /mnt/NAS/projects/2018_likith/VEP/loxodonta_africana_vep_94_loxAfr3.tar.gz --fasta /mnt/ref/LoxArf4.fasta --format vcf --input_file /mnt/data/PERG.bam_GATK.vcf --output_file /mnt/data/PERMINGIUS_G-2005_915_merged_rmdup_RG.bam_GATK.vep.vcf --fork 4 --regulatory

**Comment by ckandoth** [comment]
The error to pay attention to is `Cache directory /mnt/VEP/loxodonta_africana_vep_94_loxAfr3.tar.gz/loxodonta_africana`. This file does not exist. You need to unpack the `tar.gz` after downloading it. Please see similar instructions at https://gist.github.com/ckandoth/5390e3ae4ecf182fa92f6318cfa9fa97
