### ISSUE TITLE
Not able to convert VCF to MAF

### ISSUE THREAD

**Issue by pinninti19** [mskcc/vcf2maf#206]
Well this time, I tried with uncompressed folder, still facing the same error ?
For VEP  --> I exported the PATH
For VEP DATA --> I provided the data (uncompressed folder)

**CMD**
 **./vcf2maf.pl --input-vcf /mnt/NAS/projects/2018_likith/M.perminguis/PERMINGIUS_G-2005_915_merged_rmdup_RG.bam_GATK.vcf --output-maf /mnt/NAS/projects/2018_likith/M.perminguis/PERMINGIUS_G-2005.maf --species loxodonta_africana --filter-vcf 0  --ref-fasta /mnt/NAS/projects/2018_likith/ref/LoxArf4.fasta --vep-path /usr/local/softw/ensembl-vep --vep-data /mnt/NAS/projects/2018_likith/VEP/loxodonta_africana/**
STATUS: Running VEP and writing to: /mnt/NAS/projects/2018_likith/M.perminguis/PERMINGIUS_G-2005_915_merged_rmdup_RG.bam_GATK.vep.vcf

-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /mnt/NAS/projects/2018_likith/VEP/loxodonta_africana//loxodonta_africana not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311
STACK Bio::EnsEMBL::VEP::CacheDir::init /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /usr/local/softw/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /usr/local/softw/ensembl-vep/vep:224
Date (localtime)    = Fri Dec 21 21:20:01 2018
Ensembl API version = 94
---------------------------------------------------

ERROR: Failed to run the VEP annotator! Command: /usr/bin/perl /usr/local/softw/ensembl-vep/vep --species loxodonta_africana --assembly GRCh37 --offline --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --pubmed --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir /mnt/NAS/projects/2018_likith/VEP/loxodonta_africana/ --fasta /mnt/NAS/projects/2018_likith/ref/LoxArf4.fasta --format vcf --input_file /mnt/NAS/projects/2018_likith/M.perminguis/PERMINGIUS_G-2005_915_merged_rmdup_RG.bam_GATK.vcf --output_file /mnt/NAS/projects/2018_likith/M.perminguis/PERMINGIUS_G-2005_915_merged_rmdup_RG.bam_GATK.vep.vcf --fork 4 --regulatory

**Comment by ckandoth** [comment]
Per the error message, I would assume you need to specify `--vep-data /mnt/NAS/projects/2018_likith/VEP` not `--vep-data /mnt/NAS/projects/2018_likith/VEP/loxodonta_africana`
