### ISSUE TITLE
vcf2maf: WARNING: Couldn't retrieve bps around chrX:YYYYYY... for annotating multi-sample vcf

### ISSUE THREAD

**Issue by geejaytee** [mskcc/vcf2maf#210]
Whenever I try to annotate my multi-sample vcf files (between 14 and 142 samples, consisting of 2544 up to 6947 variants) I repeatedly get the following line

    WARNING: Couldn't retrieve bps around chrX:YYYYYY from reference FASTA: <FASTA path>

I can `samtools faidx` the `<FASTA path>`, and reducing the `--buffer-size` all the way down to 1 doesn't remove the warnings, as suggested in other issue.

However, I do seem to get VEP-annotated vcfs out of this first stage, and a valid multi-sample maf-file. Should I ignore the warning? 

I'm attaching the first part of the 14-sample VCF file if you want to try to replicate:
[ANR_top_250.vcf.zip](https://github.com/mskcc/vcf2maf/files/2783306/ANR_top_250.vcf.zip)
EDIT: to remove some specific info

**Comment by geejaytee** [comment]
Actually. I think I've found the issue - the FASTA file has >X:y-z headers but the vcfs have chrX:y-z instead, so samtools can't find chromosomes labelled "chrX" when they exist as "X"

**Comment by ckandoth** [comment]
Awesome! Glad you found the issue.
