### ISSUE TITLE
Failed to run vcf2maf

### ISSUE THREAD

**Issue by craigdj91** [mskcc/vcf2maf#211]
Hello,

I downloaded perl5 and VEP according to https://gist.github.com/ckandoth/f265ea7c59a880e28b1e533a6e935697 but I'm still having trouble when trying to run the vcf2maf.pl on the test files. Here is the command followed by the error I keep getting:

perl vcf2maf.pl --ref-fasta homo.sapiens.hg19.fa --input-vcf tests/test.vcf --output-maf tests/test.vep.maf --vep-path ~/vep --vep-data ~/.vep

STATUS: Running VEP and writing to: tests/test.vep.vcf
Can't locate CGI.pm in @INC (you may need to install the CGI module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/willey/vep/variant_effect_predictor.pl line 46.
BEGIN failed--compilation aborted at /home/willey/vep/variant_effect_predictor.pl line 46.

ERROR: Failed to run the VEP annotator! Command: /usr/bin/perl /home/willey/vep/variant_effect_predictor.pl --species homo_sapiens --assembly GRCh37 --offline --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --pubmed --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir /home/willey/.vep --fasta homo.sapiens.hg19.fa --format vcf --input_file tests/test.vcf --output_file tests/test.vep.vcf --fork 4 --check_allele --polyphen b --gmaf --maf_1kg --maf_esp --regulatory

Do you see anything obvious that I can correct quickly?

Thanks!

**Comment by ckandoth** [comment]
`CGI.pm` is one of the perl modules that should have been installed when you follow [these instructions](https://gist.github.com/ckandoth/c16b9a423b54dc0a7a37#file-build_perl_5_22-txt-L26). Try installing just that module using `curl -sL https://cpanmin.us | $PERL_BASE/perl-5.22.2/bin/perl - --notest -l $PERL_BASE/perl-5.22.2 CGI`. If it complains with an error, then post the error here, so we can debug.

**Comment by ckandoth** [comment]
No response. Closing issue.
