### ISSUE TITLE
make chunk size a cmd line parameter

### ISSUE THREAD

**Issue by lentaing** [mskcc/vcf2maf#213]
I'm running vcf2maf.pl on different instances on the cloud and I am sometimes required to modify the chunk size to fit the available memory of the machine (see issue 105).  It would be great if chunk-size were not hard-coded (at lines 313 and 336), but is an optional cmd line parameter that would override the defaults.

**Comment by ckandoth** [comment]
You might not be using the latest version `v1.6.16` which includes [this commit](https://github.com/mskcc/vcf2maf/commit/7f3bd61), where `--buffer-size` will adjust that chunk size too. Let me know if that helps.
