### ISSUE TITLE
WARNING: 19311 : Use of uninitialized value $f1_end in numeric ge (>=) at /home/alex2/anaconda3/envs/exome-seq/share/ensembl-vep-95.1-0/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm line 83, <__ANONIO__> line 3521.

### ISSUE THREAD

**Issue by alex84425** [mskcc/vcf2maf#214]
Hello everyone!
When I try the command below,and  the warning occur.

```
perl vcf2maf.pl --input-vcf 001.vcf --output-maf 001.maf --ref-fasta /Public_Resources/Illumina_Genome/iGenome/Homo_sapiens/NCBI/build37.2/Sequence/WholeGenomeFasta/genome.fa


WARNING: 14505 : Use of uninitialized value $f1_end in numeric ge (>=) at /home/alex2/anaconda3/envs/exome-seq/share/ensembl-vep-95.1-0/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm line 83, <__ANONIO__> line 6282.
```
```
Use of uninitialized value $f1_end in numeric ge (>=) at /home/alex2/anaconda3/envs/exome-seq/share/ensembl-vep-95.1-0/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm line 83, <__ANONIO__> line 6282.

```
Reads are aligned to GRCh37 reference downloaded from ensembl.
```
/home/alex2/.vep/homo_sapiens/95_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz
```
And vcf file are generated by Varscan.

I install vcf2maf by using conda, and I am sure that is also install VEP in 95_release.

Here is my $vep_data:

![image](https://user-images.githubusercontent.com/26201458/52694456-bfc4d280-2fa4-11e9-805d-b60bbab2ae50.png)

I have no idea why this error will occur.
Anyone has same problem?

**Comment by ckandoth** [comment]
That looks like a warning (not an error) coming from your VEP installed at `home/alex2/anaconda3/envs/exome-seq/share/ensembl-vep-95.1-0/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm`. If you get an output successfully, and your MAF looks fine, then you can ignore the warning message. vcf2maf v1.6.12 has only been tested with VEP v92, and not with v95, but it should work fine.

**Comment by ckandoth** [comment]
No response. Closing issue. If you are still having the issue with the latest version of VEP and vcf2maf, then please open a new issue.
