### ISSUE TITLE
Dockerfile -  returned a non-zero code: 1

### ISSUE THREAD

**Issue by TakaYamaguchi** [mskcc/vcf2maf#216]
Hello,

I just tried to build the dockerfile but got the error below.

! Installing the dependencies failed: Module 'XML::DOM' is not installed
! Bailing out the installation for XML-DOM-XPath-0.14.
! Installing the dependencies failed: Module 'XML::DOM' is not installed, Module 'XML::LibXML::Reader' is not installed, Module 'GD' is not installed, Module 'XML::LibXML' is not installed, Module 'XML::DOM::XPath' is not installed, Module 'XML::Twig' is not installed, Module 'XML::Parser::PerlSAX' is not installed
! Bailing out the installation for BioPerl-1.7.5.
--> Working on Module::Build
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/Module-Build-0.4224.tar.gz ... OK
Configuring Module-Build-0.4224 ... OK
Building and testing Module-Build-0.4224 ... OK
Successfully installed Module-Build-0.4224 (upgraded from 0.4003)
87 distributions installed
The command '/bin/sh -c cpanm CPAN::Meta        Archive::Zip    DBI     DBD::mysql      JSON    DBD::SQLite     Set::IntervalTree       LWP     LWP::Simple     Archive::Extract Archive::Tar     Archive::Zip    CGI     Time::HiRes     Encode  File::Copy::Recursive   Perl::OSType    Module::Metadata version        Bio::Root::Version      TAP::Harness    Module::Build' returned a non-zero code: 1

Thanks,

Taka

**Comment by ckandoth** [comment]
Thanks for reporting this. It has been fixed in the latest dockerfile - https://github.com/mskcc/vcf2maf/blob/master/Dockerfile - and will be released in vcf2maf v1.6.17.

**Comment by TakaYamaguchi** [comment]
Thanks for the quick response!

Taka

**Comment by TakaYamaguchi** [comment]
Hi ckandoth,

I tried the updated Dockerfile yesterday but it didn't build. Can you please look into it?

! Installing the dependencies failed: Module 'XML::LibXML' is not installed, Module 'XML::LibXML::Reader' is not installed
! Bailing out the installation for BioPerl-1.7.5.
32 distributions installed
**The command '/bin/sh -c cpanm --notest Bio::Root::Version' returned a non-zero code: 1**

Thanks,

Taka

**Comment by TakaYamaguchi** [comment]
Let me open a new ticket as this ticket was already closed.

Thanks,

Taka
