### ISSUE TITLE
Variants being assigned to wrong sample

### ISSUE THREAD

**Issue by ckandoth** [mskcc/vcf2maf#22]
maf2maf v1.6.1 with VEP v81 was run on our Luna cluster with the following I/O:

    INPUT = /ifs/res/pwg/data/tcga_mafs/debug/tcga_blca_from_dcc.maf
    OUTPUT = /ifs/res/pwg/data/tcga_mafs/debug/tcga_blca_from_dcc.vep.maf

Note that the output MAF has more variants than the input. On closer look, it's because maf2maf doesn't seem to properly handle when the tumor ID has more than one matched normals. Please fix by adding normal ID to variant hash keys.

**Comment by qwangmsk** [comment]
the bug was fixed
