### ISSUE TITLE
Why does vcf2maf filter out CNV / Fusion/ ProcControl / RNAExonVariant  ?

### ISSUE THREAD

**Issue by lakhujanivijay** [mskcc/vcf2maf#223]
I have a vcf file which have few rows with following type of data and I could observe that all of this is being filtered out. 

```
grep -v "^#" sample1_pateint1.vcf | grep -Po "SVTYPE=\w+"  | sort | uniq -c
      1 SVTYPE=CNV
     94 SVTYPE=Fusion
      2 SVTYPE=ProcControl
      4 SVTYPE=RNAExonVariant
```
My command is :

`vcf2maf.pl --input-vcf sample1_pateint1.vcf --output-maf sample1_pateint1.maf  --ref-fasta  genome.fa  --filter-vcf 0 --vep-path /home/bioinfo/variant-effect-predictor-87-0/bin/  --custom-enst isoform_overrides_uniprot.txt --tumor-id sample1`

Can you tell us why is this happening?

**Comment by ckandoth** [comment]
Except for `CNV`, those are not valid values for `SVTYPE` as defined in [VCF 4.2 specs](https://samtools.github.io/hts-specs/VCFv4.2.pdf). See [this line of code](https://github.com/mskcc/vcf2maf/blob/v1.6.21/vcf2maf.pl#L298) in vcf2maf to see how SVs are handled. Briefly, SVs of type `BND, TRA, DEL, DUP, or INV` are split into two VCF lines for two breakpoints and they are fed into Ensembl VEP as point mutations. This is hacky, but it was the only way to generate the `Gene1::Gene2` format for gene fusions that the [cBioPortal importer](https://docs.cbioportal.org/file-formats/#fusion-data) liked to parse. This is old hacky code, so YMMV. It looks like the cBioPortal deprecated the Fusion format in favor of a more structured SV format.
