### ISSUE TITLE
Retrieve tumor id from the vcf meta data

### ISSUE THREAD

**Issue by wod31** [mskcc/vcf2maf#226]
Hi, 

I want to run vcf2maf with some vcf files but the tumor id is in the metadata (##INDIVIDUAL) and not in the TUMOR column. How can i specify this option to the vcf2maf script? 

Many thanks.

**Comment by ckandoth** [comment]
You can extract the tumor-id from the `##INDIVIDUAL` using unix grep/cut, or manually if you don't have too many VCF files. And then use that with vcf2maf's `--tumor-id` ID argument. But make sure that `--vcf-tumor-id` matches the actual name of the genotype column in the VCF. I assume the column header is `TUMOR` as you indicated.
