### ISSUE TITLE
ERROR: Unfortunately, --input-vcf cannot be in a compressed format

### ISSUE THREAD

**Issue by willemdek11** [mskcc/vcf2maf#235]
Can this please be in the next update?

Is there a way around this, I have multiple compressed vcf files and I'm not looking forward to unpack them all.

Thanks!

**Comment by ckandoth** [comment]
Hi @willemdek11. If your gzipped VCFs are enormous, you should run false-positive filters to shortlist the candidate events to report in MAF format. During that step, you can have it generate an uncompressed VCF for input to vcf2maf.

I once attempted stdin/stdout streaming to allow in-memory gzipped input, but it became too complex. Even if vcf2maf supported compressed VCFs as input, it would still need to uncompress them somewhere on your disk. So the benefits outweigh the added complexity to the code.
