### ISSUE TITLE
Install Problems in a university cluster

### ISSUE THREAD

**Issue by Lesdormis** [mskcc/vcf2maf#238]
Dear maf2vcf developers,

I have some difficulty to try to install the maf2vcf to my university cluster, especially for the VEP part.
Do you have a more informative and simple tutorial about how to install it?

Thanks so much

**Comment by Lesdormis** [comment]
It seems I stuck in this step:
Convert the offline cache for use with tabix, that significantly speeds up the lookup of known variants:

perl convert_cache.pl --species homo_sapiens --version 86_GRCh37 --dir $VEP_DATA

It shows up with this ERROR
Can't locate Bio/EnsEMBL/Utils/Exception.pm in @INC (you may need to install the Bio::EnsEMBL::Utils::Exception module) (@INC contains: /gpfs/home/sj2641/ensembl-vep/modules /gpfs/home/sj2641/ensembl-vep /gpfs/share/apps/perl/5.28.0/lib/5.28.0 /gpfs/home/sj2641/perl5/lib/perl5 /gpfs/share/apps/perl/5.28.0/lib/site_perl/5.28.0/x86_64-linux /gpfs/share/apps/perl/5.28.0/lib/site_perl/5.28.0 /gpfs/share/apps/perl/5.28.0/lib/5.28.0/x86_64-linux) at /gpfs/home/sj2641/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 60.
BEGIN failed--compilation aborted at /gpfs/home/sj2641/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 60.
Compilation failed in require at convert_cache.pl line 50.
BEGIN failed--compilation aborted at convert_cache.pl line 50.

**Comment by ckandoth** [comment]
The README now links to much simpler instructions using conda - https://gist.github.com/ckandoth/61c65ba96b011f286220fa4832ad2bc0 - please open an issue if you have trouble with this.
