### ISSUE TITLE
Does Reference_Allele mean allele in the reference genome? 

### ISSUE THREAD

**Issue by singletrips** [mskcc/vcf2maf#239]
Is Reference_Allele is allele in the reference genome?  What's the difference between Reference_Allele and Alternative_Allele? Does Alternative_Allele mean allele in the patient we are studying?

**Comment by ckandoth** [comment]
Yes, `Reference_Allele` is usually the allele in the reference genome. But not that vcf2maf is simply copying whatever it sees in the `REF` field in the input VCF. Hopefully, whoever created the VCF is correctly pulling the allele from the reference FASTA.
