### ISSUE TITLE
ALLELE_NUM undefined for some variants

### ISSUE THREAD

**Issue by ckandoth** [mskcc/vcf2maf#24]
ALLELE_NUM for some reason is not always present in *.vep.vcf file, which causes some downstream problems (precisely this fragment is crashing: 

    # Skip effects on other ALT alleles
    push( @all_effects, \%effect ) if( $effect{ALLELE_NUM} == $var_allele_idx );)

**Comment by egrabowska** [comment]
test variant:
5	67591092	.	G	GTAT

**Comment by ckandoth** [comment]
Unable to reproduce this by running vcf2maf on the test variant. The vep.vcf file generated by VEP appears to contain the ALLELE_NUM as 1. Going to put this on hold. Let me know what you find. Note that I used VEP v82.

**Comment by ckandoth** [comment]
In [this issue](https://github.com/mskcc/vcf2maf/issues/30), we found that VEP will not report `ALLELE_NUM` for variants with `SVTYPE` defined in the input VCF's `INFO` field. I'm going to assume this is what happened in your case too. Regardless, I have pushed a fix that should handle this situation gracefully. But the recommendation is to remove `SVTYPE` from your VCF if it is simply a small indel. VEP seems to limit the information it reports, based on the specs that `SVTYPE` is for larger structural variants. Closing this issue, but feel free to reopen if you find more information on this.

Thanks again for reporting!

**Comment by egrabowska** [comment]
Thanks for spotting the problem and fixing it!
Indeed, the variant I reported had "SVTYPE=INS" in the INFO field (Pindel always adds SVTYPE).

**Comment by ckandoth** [comment]
@liangkaiye FYI. `SVTYPE` gets interpreted as a larger structural variant by VEP in downstream pipelines, and calculation of consequence on the protein sequence is skipped.
