### ISSUE TITLE
missing t_depth/t_alt_count/t_ref_count fields in MAF files

### ISSUE THREAD

**Issue by ltang217** [mskcc/vcf2maf#240]
hi, I have problem getting t_depth/t_alt_count/t_ref_count information for all SNVs from VCF files. I checked that my vcf file does contain 'GT:AD:AF:DP' under tumor sample column, but in the converted maf file, some variants get 't_depth/t_ref_count/t_alt_count', but some others not. And this happens on both SNV and small INDELs. Very confusing. Anyone can help look into this? I can provide the sample vcf files. Thanks!

**Comment by ckandoth** [comment]
@ltang217 this usually happens if you forget to specific `--tumor-id` or `--vcf-tumor-id`. If that is not the issue, then please share your command-line usage, and a sample VCF. Thanks.

**Comment by sunqiangzai** [comment]
@ckandoth, Thank you for your advice, add --vcf-tumor-id and --vcf-normal-id works.
