### ISSUE TITLE
Failed to synchronize cache for repo 'AppStream', ignoring this repo. The command '/bin/sh -c yum install wget java-1.8.0-openjdk-devel -y' returned a non-zero code: 1

### ISSUE THREAD

**Issue by paramacharya** [mskcc/vcf2maf#241]
Hi Everyone,
I am under corporate proxy( some-proxy.us.com and I am trying to install wget and java inside my container, and I am unable to do it. getting an error as follows
Her is my Dockerfile

FROM centos
RUN yum install wget java-1.8.0-openjdk-devel -y

Failed to synchronize cache for repo 'AppStream', ignoring this repo. 
The command '/bin/sh -c yum install wget java-1.8.0-openjdk-devel -y' returned a non-zero code: 1
Please help me . Please help me , I am stuck with my work, resolutio can share with me on gajulapavans@gmail.com

**Comment by ckandoth** [comment]
Hi @paramacharya. Sorry you are encountering issues with your corporate proxy. You should contact your IT department. I'm also not sure if you are trying to install vcf2maf.
