### ISSUE TITLE
vcf2maf error: Can't locate Bio/PrimarySeqI.pm in @INC

### ISSUE THREAD

**Issue by matnguyen** [mskcc/vcf2maf#243]
I installed VEP through Conda, yet it seems to be missing a dependency:

`STATUS: Running VEP and writing to: ../results/08-MAF/DLC0001/DLC0001.onpass.filtered.vep.vcf
Can't locate Bio/PrimarySeqI.pm in @INC (you may need to install the Bio::PrimarySeqI module) (@INC contains: /home/mnguyen/anaconda3/pkgs/variant-effect-predictor-87-0/share/variant-effect-predictor-87-0 /home/mnguyen/anaconda3/envs/bioinformatics/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/mnguyen/anaconda3/envs/bioinformatics/lib/site_perl/5.26.2 /home/mnguyen/anaconda3/envs/bioinformatics/lib/5.26.2/x86_64-linux-thread-multi /home/mnguyen/anaconda3/envs/bioinformatics/lib/5.26.2 .) at /home/mnguyen/anaconda3/pkgs/variant-effect-predictor-87-0/share/variant-effect-predictor-87-0/Bio/EnsEMBL/Slice.pm line 75.`

**Comment by Kekananen** [comment]
Yes, this is more of a BioPerl conda problem I think then a VEP one.  I installed BioPerl core package via conda and it fixed that issue right up; however, be warned that there are other underlying issues with installing with conda that may pop up. I ended up having to build from source due to this to avoid followup issues.

**Comment by ckandoth** [comment]
I had this happen sometimes after a fresh conda installation. The solution was to logout, login, then `conda activate`, and then the Perl modules would be properly loaded into `@INC` for other Perl scripts to find and use. The issue should not happen again. Let me know if it persists.

**Comment by gaom001** [comment]
Is there is a clear answer for this?   Thanks

**Comment by abhisheksiroha** [comment]
above issue is still there

**Comment by yjjin9024** [comment]
I solved this problem by installing "perl-bioperl-core".

https://anaconda.org/bioconda/perl-bioperl-core
