### ISSUE TITLE
Strange Behavior Regarding Chromosomes

### ISSUE THREAD

**Issue by Slavatron** [mskcc/vcf2maf#245]
I am trying to run vcf2maf.pl on a VCF file that used GRCh38 as the reference genome and something strange seems to be happening with the VEP command. Here's what my command looks like:

`vcf2maf.pl --input-vcf /LocalDir/HC_9897.vcf --output-maf /LocalDir/HC_9897.maf --vep-data /LocalDir/VEP --ref-fasta /LocalDir/VEP/homo_sapiens/99_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --filter-vcf /LocalDir/ExAC_nonTCGA.r0.3.1.sites.vep.vep.vcf.gz --ncbi-build GRCh38
`

When I first ran this command it produced a file named HC_9897.vep.vcf that contained only the top sections of a VCF but no variants:

```
$ tail -1 HC_9897.vep.vcf 
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	832_A_S28517

```

Similarly, the MAF file produced only contained a header. Because I got a lot of warnings like this:
`WARNING: Couldn't retrieve bps around chr19:53824059 from reference FASTA: /LocalDir/VEP/homo_sapiens/99_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz
`
I thought the problem might be that my VCF names chromosomes with the "chr" prefix and the reference FASTA file does not. As a test, I modified a few variants in my VCF to change "chr1" to "1" and ran vcf2maf.pl again. 

This is where things get strange: the *.vep.vcf file produced contained both variants that had the "chr" prefix stripped as well as some that did not. Thinking this might have something to do with memory issues, I dramatically reduced the size of my input VCF and ran the same vcf2maf.pl command again and found that this actually returned ALL of the variants present despite the inconsistent way their chromosomes were named.  I have attached two sets of *.vcf, *.vep.vcf, *.maf files to help explain this strange behavior; the ones named "modified_HC..." were from the first attempt to modify the VCF. 
[strange_vcf2maf.zip](https://github.com/mskcc/vcf2maf/files/4277203/strange_vcf2maf.zip)

Any insight into how/why this is happening would be much appreciated. Also welcome any advice on how to convert my GRCh38 VCF files to MAFs without having to change the chromosome naming convention. 
Thanks!

**Comment by ckandoth** [comment]
Hi @Slavatron. Ideally, `--ref-fasta` should be the same FASTA that was used to generate your VCF files. If this is the GRCh38 FASTA from NCBI or GATK, then use that instead. The GRCh38 reference FASTA from Ensembl does not use the chr-prefix, and this causes everyone a world of problems. I will try to change the default GRCh38 reference FASTA in my installation instructions.
