### ISSUE TITLE
vcf2maf VEP annotated VCF conversion

### ISSUE THREAD

**Issue by Martulie** [mskcc/vcf2maf#247]
Hello, I heard many times about possibility to convert annotated vcf to maf with vcf2maf by rewriting of input name to *.vep.vcf (which marks that vcf is already annotated). But even when I do it, the vcf2maf program wants to annotate it again, which I don't want. Can you please advice me how to make it work without annotation?

$ vcf2maf.pl --input-vcf input.vep.vcf --output-maf output.vep.maf --vcf-tumor-id input_TUMOR --vcf-normal-id input_NORMAL --tumor-id input_TUMOR normal-id input_NORMAL --buffer-size 100  --ref-fasta
/exports/eddie/scratch/s1959373/external/human_g1k_v37.fasta --filter-vcf 0

STATUS: Running VEP and writing to: ./input.vep.vep.vcf
ERROR: Cannot find VEP script in path: /home/..

Thank you very much!

Martina

**Comment by Martulie** [comment]
Problem solved, both *vep.vcf and *.vcf need to be available

**Comment by ckandoth** [comment]
Hello @Martulie. I just released [v1.6.18](https://github.com/mskcc/vcf2maf/releases/tag/v1.6.18), where this workaround is no longer available, but you can use `--inhibit-vep` to safely skip VEP. It will still attempt to extract VEP data from your VCF as best as possible. Feel free to re-open this issue if you encounter errors or warnings. Thanks.
