### ISSUE TITLE
Cant execute -- cat $VEP_DATA/*_vep_$VER\_GRC{h37,h38,m38}.tar.gz | tar -izxf - -C $VEP_DATA

### ISSUE THREAD

**Issue by ankurnaqib** [mskcc/vcf2maf#251]
Hi,
I followed all the steps mentioned on the website. All works fine until
cat $VEP_DATA/*_vep_$VER\_GRC{h37,h38,m38}.tar.gz | tar -izxf - -C $VEP_DATA

This throws me an error
-bash-4.2$ cat $VEP_DATA/*_vep_$VER\_GRC{h37,h38,m38}.tar.gz | tar -izxf - -C $VEP_DATA
cat: /home/.vep/*_vep_95_GRCh37.tar.gz: Not a directory
cat: /home/.vep/*_vep_95_GRCh38.tar.gz: Not a directory
cat: /home/.vep/*_vep_95_GRCm38.tar.gz: Not a directory

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Please help.

**Comment by ckandoth** [comment]
@ankurnaqib please follow the latest instructions to install VEP. See https://gist.github.com/ckandoth/61c65ba96b011f286220fa4832ad2bc0
