### ISSUE TITLE
WARNING: Unrecognized biotype "lncRNA". Assigning lowest priority!

### ISSUE THREAD

**Issue by Nickier0510** [mskcc/vcf2maf#252]
Hi, when I run this script vcf2maf.pl, it reminds me: WARNING: Unrecognized biotype "lncRNA". Assigning lowest priority! Is it necessary to update the script?
My vcf file is output by vep, version=100.
My vcf2maf was installed in 29 May, 2020

**Comment by dongjoban17** [comment]
You might want to check the current pulled request (#249 ) which discusses exactly this. I changed the mapping from lincRNA to lncRNA in the script to avoid the warnings as a temporary solution.

**Comment by Nickier0510** [comment]
OK~ Thanks a lot.

**Comment by ckandoth** [comment]
Thanks for helping with this @djb17. Also try version v1.6.21 released yesterday. Closing issue.
