### ISSUE TITLE
Running vcf2maf.pl with VEP Plugin

### ISSUE THREAD

**Issue by whitejaa** [mskcc/vcf2maf#258]
Hello,

I would like to use vcf2maf to annotate my vcfs with dbNSFP annotations; however, I am not sure how to invoke the use of VEP plugins. I am running the command below. The vcf2maf manual mentions that the --vep-data argument should be the path to the VEP plugin directory but that is all the info I can find. Thanks for the help!

vcf2maf.pl --input-vcf /data/whitejaa/Nigerian_WES/CCBR_Output/PPBSw1Normal/merged_somatic_variants/Annovar/VEP_test/Tum-387_S16.merged.vcf \
--output-maf /data/whitejaa/Nigerian_WES/CCBR_Output/PPBSw1Normal/merged_somatic_variants/Annovar/VEP_test/Tum-387_S16.merged.maf \
--retain-info set --vep-path $VEP_HOME --vep-data $VEPCACHEDIR \
--ref-fasta /data/CCBR_Pipeliner/db/PipeDB/lib/hs37d5.fa \
--filter-vcf /fdb/VEP/88/cache/ExAC.r0.3.sites.vep.vcf.gz \
--vep-forks 6 \
--vcf-tumor-id Tum-387_S16 --vcf-normal-id N-338_S7 \
--tumor-id Tum-387_S16 --normal-id N-338_S7 \
--ncbi-build GRCh37 \
--species homo_sapiens

**Comment by ckandoth** [comment]
vcf2maf does not support invoking VEP plugins, but you can run VEP with plugins manually, and then run vcf2maf with `--inhibit-vep` to skip re-running VEP, and use `--retain-info` or `--retain-format` to extract the additional fields you want to extract into new columns in the MAF. See the [documentation here](https://github.com/Ensembl/VEP_plugins/blob/release/101/dbNSFP.pm) to setup the dbNSFP plugin for VEP.
