### ISSUE TITLE
GNU parallel with vcf2maf

### ISSUE THREAD

**Issue by nickhir** [mskcc/vcf2maf#259]
I am trying to use GNU parallel to run vcf2maf in parallel.

My command looks something like this:

```
${parallel} --link "perl ${vcf2maf} --input-vcf ${1} \
                                    --output-maf ${maf_dir}/${2}.maf \
                                    --tumor-id ${3} \
                                    --tmp-dir ${vcf_dir} \
                                    --vep-path ${vep_script} \
                                    --vep-data ${vep_data} \
                                    --ref-fasta ${fasta} \
                                    --filter-vcf ${filter_vcf}" :::: ${VCF_files} ${results} ${tumor_ids}
```

```VCF_files```, ```results``` and ```tumor_ids``` contain one entry per line and correspond to one another.

When I try and run the command I get the following error for every file:

```ERROR: Both input-vcf and output-maf must be defined!```

This confused me, because if I run the command manually, the program works as intended, so I dont think that the input/outpit paths are wrong. To confirm this, I also ran

```${parallel} --link "cat ${1}" :::: ${VCF_files} ${results} ${tumor_ids}```, which correctly prints the contents of the VCF files, whose path is listed in VCF_files.

I am really confused what I did wrong, if anyone could help me out, I'd be very thankful!

Thanks!

**Comment by ckandoth** [comment]
@nickhir Note that vcf2maf has a `--vep-forks` option which takes advantage of multicore CPUs when running VEP, the most compute intensive step. It is set to 4 forks by default. You can increase this to fully use all your CPU threads. I would recommend this instead of GNU parallel.
