### ISSUE TITLE
Can I provide multiple transcript-list to vcf2maf?

### ISSUE THREAD

**Issue by YangShi-PKU** [mskcc/vcf2maf#263]
Hi,
First thanks for developing such a wonderful tool! I want to use it to annotate my mutation VCF file from HCC. I want to use the MSKCC transcript list first; and if the gene isn't in that list, I want to use MANE select transcripts; otherwise, I want to use APPRIS top-level transcripts. 
Indeed, my aim is similar with the function in [Funcotator](https://gatk.broadinstitute.org/hc/en-us/articles/360035889931-Funcotator-Information-and-Tutorial)

> Choose the transcript that is on the custom list specified by the user. If no list was specified, treat as if all transcripts were on the list (tie).
> In case of tie, choose the transcript with highest level of curation. Note that this means lower number is better for level (see below).
> If still a tie, choose the transcript that yields the variant classification highest on the variant classification rank list (see below).
> If still a tie, choose the transcript with the best appris annotation (see below).
> If still a tie, choose the transcript with the longest transcript sequence length.
> If still a tie, choose the first transcript, alphabetically.

Can I provide multiple transcript list to VCF2MAF? Or can I add some parameters to enable such multi-level transcription selection?

Thanks
Yang

**Comment by ckandoth** [comment]
@YangShi-PKU This is somewhat possible by providing multiple transcript IDs per gene in `--custom-enst`. For example, [two isoforms are listed here](https://github.com/mskcc/vcf2maf/blob/v1.6.19/data/isoform_overrides_at_mskcc#L80-L81) for CDKN2A. The isoform with the most severe effect is reported in MAF format, though effects on all transcripts are reported in the `all_effects` column. If two or more isoforms are affected the same (e.g. missense), the longest transcript is preferred.

**Comment by YangShi-PKU** [comment]
Hi @ckandoth 
Thanks for your suggestion, but it's a bit of different from my purpose. Because I want to use MSKCC list firstly, yet the transcript in this list may not be the one that has the most severe effect. Can I select the MSKCC list as the list with top priority?

Yang
