### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by Martulie** [mskcc/vcf2maf#264]
Hello, do you have some prefered format for vcf2maf citation?

**Comment by ckandoth** [comment]
Hi @Martulie. Thanks for using vcf2maf. Can you tell me which version you used, and I'll generate a DOI.

**Comment by ckandoth** [comment]
Actually, I just found that you can use `doi:10.5281/zenodo.593251` regardless of version. The citation would look like:
```
Cyriac Kandoth. mskcc/vcf2maf: vcf2maf v1.6.18. (2020). doi:10.5281/zenodo.593251
```

**Comment by Martulie** [comment]
Hello Cyriac, thank you very much! 
Have a nice day :-)
