### ISSUE TITLE
Returning empty sequence error?

### ISSUE THREAD

**Issue by vymao** [mskcc/vcf2maf#265]
Hi, I am getting an error when I try to run `maf2vcf.pl`, and I am not sure why: 

```
[W::fai_get_val] Reference chr20:18143315-18143317 not found in file, returning empty sequence
[faidx] Failed to fetch sequence in chr20:18143315-18143317
[W::fai_get_val] Reference chr7:86415876-86415878 not found in file, returning empty sequence
[faidx] Failed to fetch sequence in chr7:86415876-86415878
ERROR: Make sure that ref-fasta is the same genome build as your MAF
```

I am fairly certain I am using the correct reference (GRCh37). Is it because these locations aren't found in the reference? It seems strange to me that this would be the case, because I checked the reference and these are valid locations.

**Comment by ckandoth** [comment]
It is likely that your reference genome does not have the `chr` prefix for chromosome names. Let me know otherwise.
