### ISSUE TITLE
Could I retain genotype field of original vcf?

### ISSUE THREAD

**Issue by stellaoh** [mskcc/vcf2maf#266]
Dear vcf2maf team, 

######### [Solved] #########
This is genotype information in my raw vcf. 

![image](https://user-images.githubusercontent.com/33537478/92061745-0326a200-edd2-11ea-9ec0-d25c2f4a77b8.png)

I want to retain this genotype information in final MAF. 

Can I get this result from vcf2maf? 
###########################

-> I found solution.

**But, there is a bug.** 

1) This is input vcf (Genotype is 0/0)
![image](https://user-images.githubusercontent.com/33537478/92079203-7e9c4980-edfa-11ea-98a9-2e7c6e356ab7.png)

2) Output maf (using "--retain-fmt GT")
![image](https://user-images.githubusercontent.com/33537478/92079289-9c69ae80-edfa-11ea-9dee-afe764bfb4fa.png)

Thanks.

**Comment by ckandoth** [comment]
Can you share the full command to reproduce the bug? I suspect that `--tumor-id` or `--tumor-vcf-id` is not specified. So vcf2maf uses the default GT of `0/1`.

**Comment by ckandoth** [comment]
Closing issue. It is likely that OP did not specify `--tumor-id` in their command.
