### ISSUE TITLE
maf2vcf.pl error

### ISSUE THREAD

**Issue by gpalou4** [mskcc/vcf2maf#267]
Hi,

I am trying to use maf2vcl.pl but it gives me an error. The .MAF file is the MC3 from TCGA data and GRCh37 version (https://gdc.cancer.gov/about-data/publications/mc3-2017). I first had to fix the file changing \r for \n as it was given me an error:

`sed 's/\r/\n/' mc3.v0.2.8.PUBLIC.maf > mc3.v0.2.8.PUBLIC.fix.maf`

This is the command:

`mskcc-vcf2maf-47c4a18/maf2vcf.pl --input-maf mc3.v0.2.8.PUBLIC.fix.maf --output-dir vcfs --output-vcf vcfs --ref-fasta GRCh37-38/GRCh37.p13.fasta`

`ERROR: Invalid Tumor_Sample_Barcode in MAF: ""`

I looked at that column and there is no missing Barcode anywhere.

I even tried to use your test.maf in "tests" folder but it gave a different error:

`skcc-vcf2maf-47c4a18/maf2vcf.pl --input-maf mskcc-vcf2maf-47c4a18/tests/test.maf --output-dir vcfs --output-vcf vcfs --ref-fasta GRCh37-38/GRCh37.p13.fasta`

`ERROR: Make sure that ref-fasta is the same genome build as your MAF: GRCh37-38/GRCh37.p13.fasta`

And I downloaded the GRCh37 from here --> https://www.ncbi.nlm.nih.gov/search/all/?term=grch37.p13

Any help? Thank you!

**Comment by ckandoth** [comment]
Thanks for providing sufficient detail to reproduce your steps. The MAF uses `\r\n` at the end of each line, so you need to do `sed 's/\r//'` to remove the `\r` but retain the `\n`. By doing `sed 's/\r/\n/'` you are causing an extra `\n` to be added after each line, which creates blank lines.

Download TCGA MC3 MAF, uncompress, and fix `dos` newline:
```bash
curl -L https://api.gdc.cancer.gov/data/1c8cfe5f-e52d-41ba-94da-f15ea1337efc -o mc3.v0.2.8.PUBLIC.maf.gz
gzip -d mc3.v0.2.8.PUBLIC.maf.gz
sed -i 's/\r//' mc3.v0.2.8.PUBLIC.maf
```

Regd the other error, you are likely using the NCBI FASTA with `chr`-prefix for each chromosome, while the MAF does not need chr-prefix.

**Comment by gpalou4** [comment]
Hi Cyriac,

Thank you! I'll try again tomorrow, and let you know

Best,
Guille
