### ISSUE TITLE
Update conda package?

### ISSUE THREAD

**Issue by SRodenburg** [mskcc/vcf2maf#268]
Hello,

Could you please update the anaconda package for vcf2maf?
I am waiting for the `--inhibit-vep` fix there.
https://anaconda.org/bioconda/vcf2maf

Thanks!

**Comment by ckandoth** [comment]
I don't maintain the anaconda package. And based on [their documentation](http://bioconda.github.io/recipes/vcf2maf/README.html), I'm not sure who you should reach out to. My recommendation is to use the vcf2maf Perl script as is. All its other dependencies can be installed with conda as [described here](https://gist.github.com/ckandoth/61c65ba96b011f286220fa4832ad2bc0).
