### ISSUE TITLE
Adding option for extracting annotation from VCF and in the MAF

### ISSUE THREAD

**Issue by snashraf** [mskcc/vcf2maf#269]
Thanks for the amazing tool and it's been greatly useful.

Can you please add an extra option for extracting annotation from VCF and add as a separate column in MAF. 
So I will take raw VCF and add annotation using VCFANNO or BCFTOOLS and then use vcf2maf so we could have option of adding as extra column in MAF.

Thanks for the amazing work. Please let me know about any other details.

Regards,
Najeeb

**Comment by ckandoth** [comment]
Arguments `-retain-info` and `--retain-fmt` are already [in vcf2maf](https://github.com/mskcc/vcf2maf/blob/v1.6.18/vcf2maf.pl#L1145-L1146). Reopen issue if you meant something else.
