### ISSUE TITLE
custom multiple isoforms?

### ISSUE THREAD

**Issue by caaespin** [mskcc/vcf2maf#275]
Can we provide more than one RefSeq for a given gene in the file for `--custom-enst`? or those it choose just the first/last entry? We are trying to match variants in the MAF file to variants in a separate datafile that have additional manual annotations for those variants. The problem we run into is we often cannot find a match because the MAF uses a different transcript than what we have in our datafiles and in some cases the datafile has more than one RefSeq ID for a gene.

**Comment by ckandoth** [comment]
You can specify multiple isoforms per gene in `--custom-enst`, but it will not do what you want it to do. Each variant will be mapped to the worst affected isoform. What you need to parse is the `all_effects` column in the output MAF. This lists the HGVS codes for all overlapping or nearby isoforms for each variant.
