### ISSUE TITLE
refseq id confused

### ISSUE THREAD

**Issue by bioxu** [mskcc/vcf2maf#276]
Hi,
We have found that the ensembl_transcript mapping to different refseq_id between vcf2maf (isoform_overrides_uniprot file) and NCBI (https://ftp.ncbi.nlm.nih.gov/gene/DATA/gene2ensembl.gz). For example, KEAP1, ENST00000171111, the refseq_id is NM_012289.3 in the vcf2maf, while NM_203500.2 in the NCBI. So, which one is better ?

**Comment by ckandoth** [comment]
`isoform_overrides_uniprot` is not a mapping between ensembl and refseq transcripts. It is a list of preferred isoforms per gene. This can be subjective, and no isoform choice is truly better than the other.
