### ISSUE TITLE
error in `maf2maf`

### ISSUE THREAD

**Issue by blueskypie** [mskcc/vcf2maf#277]
got error from 
`perl maf2maf.pl --input-maf tests/test.maf --output-maf tests/test.vep.maf`

Error msg
>WARNING: Replacing '-' with reference allele in: PIK3CA 0       .       GRCh37  3       178936091       178936091       +    Missense_Mutation        SNP     G       -       A                       TUMOR   NORMAL  G       G                            43       21      22      11      11      0
>STATUS: Running VEP and writing to: /tmp/vyZEcwK0Vj/test.vep.vcf
>ERROR: Cannot find VEP script in path: /home/jike.cui/vep

I'm not sure what is the `VEP script`. `vcf2maf` runs w/o problem.

**Comment by ckandoth** [comment]
Hi @blueskypie. Thanks for reporting this. Depending on the vcf2maf version you are using, the option `--vep-path` might be set differently. It looks like you are using an older version where maf2maf looks for the VEP script under `~/vep` which in your case is `/home/jike.cui/vep`. Just specify wherever you install VEP, and it should work fine. E.g.

```bash
perl maf2maf.pl --input-maf tests/test.maf --output-maf tests/test.vep.maf --vep-path ~/miniconda3/bin
```
