### ISSUE TITLE
vcf2maf removal of anchor bases on complex variants 

### ISSUE THREAD

**Issue by andurill** [mskcc/vcf2maf#279]
https://github.com/mskcc/vcf2maf/blob/317fa2c2ab039345f951f8fc8f2773a5a241a3d0/maf2maf.pl#L277-L281

Hi @ckandoth,
In the code block referenced above, the prefixed reference bps (or anchor bps) from both REF and ALT alleles in vcf format are removed. Indels in vcf format include just one anchor base. Is there a reason for why you are removing the the prefixed reference bps with a while loop instead of just removing the first common base between REF and ALT?

The reason for my question is that there are certain types of complex variants that are reported by Vardict with an alternative right alignment (instead of the conventional left alignments in vcf), without anchor bases. Here is an example:

![image](https://user-images.githubusercontent.com/12943340/110830497-4709d080-8267-11eb-9876-8566a167095e.png)

This variant is reported by vardict as:
Chromosome | Start_Position | Ref | Alt
7 | 55242469 |  TTAAGAGAAG | C

We can then convert it to the format below with prefixed bases, so that it matches the CIGAR strings and genotypers can recognize and properly genotype the variant.

7 | 55242465 | GGAATTAAGAGAAG | GGAAC

However, the code-block in maf2maf referenced above will remove these anchor bases, thus converting the REF/ALT back to the right aligned format reported by vardict. Consequently, the variant will not be genotyped correctly.

I am wondering whether it make sense to update maf2maf to assume that there is only one anchor base in indels and complex variants and only remove that base while converting from vcf to maf. With this suggested change, the complex variant will have the following format in a maf file, and can be correctly genotyped.
7 | 55242466 | GAATTAAGAGAAG | GAAC

Thanks!

**Comment by andurill** [comment]
@rhshah

**Comment by rhshah** [comment]
@ckandoth can you please let us know your thoughts on this, do you think we can update maf2maf with suggested behavior.

**Comment by ckandoth** [comment]
@andurill Thanks for documenting this so well. It was implemented as a loop because VCF spec allows more than one anchor bps, though this is not commonly done. Also uncommon is using VCF spec in a MAF file. So, I agree we can remove the loop behavior, and just remove one anchor bp, if found. Working on this now, and will release as `v1.6.20` shortly.

**Comment by ckandoth** [comment]
This is now handled in https://github.com/mskcc/vcf2maf/releases/tag/v1.6.20

**Comment by rhshah** [comment]
Thank you

**Comment by inodb** [comment]
@ckandoth @andurill doesn't this result in issues when you run `maf2maf` multiple times in a row?

E.g. first time:

`7 | 55242465 | GGAATTAAGAGAAG | GGAAC` -> `7 | 55242466 | GAATTAAGAGAAG | GAAC`

Second time:

`7 | 55242465 | GAATTAAGAGAAG | GAAC` -> `7 | 55242466 | AATTAAGAGAAG | AAC`

etc





[2:28](https://mskcmo.slack.com/archives/D0412RF2P08/p1662488931260989)
7 | 55242465 | GGAATTAAGAGAAG | GGAAC -> 7 | 55242466 | GAATTAAGAGAAG | GAAC
[2:28](https://mskcmo.slack.com/archives/D0412RF2P08/p1662488932545909)
second time
[2:29](https://mskcmo.slack.com/archives/D0412RF2P08/p1662488961111349)
7 | 55242465 | GAATTAAGAGAAG | GAAC -> 7 | 55242466 | AATTAAGAGAAG | AAC

**Comment by ckandoth** [comment]
Yes, but anyone with more than one anchor bp is probably doing something wrong in their upstream pipeline. Or they have a very specific reason to do so, as OP indicated. So, I decided to meet the OP's use-case.
