### ISSUE TITLE
Write proper unit tests and plug into Jenkins

### ISSUE THREAD

**Issue by ckandoth** [mskcc/vcf2maf#28]
VEP setup is a chore and Travis CI or other container-based CI services cannot handle the data-size and pre-test setup time. We have Jenkins running on our compute cluster, where VEP is already set up. Write tests that trigger on each push to github, and send pass/fail status to a github badge.

**Comment by jchodera** [comment]
I'm just curious if you have Jenkins running on one of the MSK HPC clusters, and if so, how you have it configured for continuous integration of GitHub projects. We had to dedicate a special Jenkins server in a VPN for this.

**Comment by lordzappo** [comment]
We had no particular problems doing this, but the luna node/head node we
are using is internet capable.  Is that the difference?

We don't have full continuous integration actually running yet, we merely
run tests on push.  Most of our projects will want to keep previous
versions available, so we have to develop a versioning system that installs
each new version into its own folder for python, perl, and R code,, rather
than simply stomping on the previous version.

And for our python code, we need to rewrite our package's setup.py to
integrate github tags so we get auto version numbering there, to make this
scheme work.

https://github.com/warner/python-ecdsa/blob/9e21c3388cc98ba90877a1e4dbc2aaf66c67d365/setup.py#L33

**Comment by ckandoth** [comment]
Unit tests are now included in v1.6.7. They expect VEP script+cache to be in the default `~/vep` and `~/.vep` locations, which we handle in Jenkins with symlinks to `/opt/common/CentOS_6-dev/vep/v84`.
