### ISSUE TITLE
Convert maf to vcf

### ISSUE THREAD

**Issue by weber77** [mskcc/vcf2maf#280]
Hi guys, this is not really and issue but help request.
I've never used perl before so i need you help.

How can i use your [script](https://github.com/mskcc/vcf2maf/blob/main/maf2vcf.pl) to convert the maf file below to vcf?
[sample.maf.gz](https://github.com/mskcc/vcf2maf/files/6237233/sample.maf.gz)

I'll greatly appreciate your help.

Weber Dubois
Email: weberkanga77@gmail.com

**Comment by ckandoth** [comment]
@weber77 make sure you have samtools installed. Then unzip your MAF as follows:
```bash
gzip -d sample.maf.gz
```
Then you can run `maf2vcf.pl` as follows:
```bash
perl ~/src/vcf2maf/maf2vcf.pl --input-maf sample.maf --per-tn-vcfs --output-dir sample_vcfs --ref-fasta /mdl/ref/GCA_000001405.15_GRCh38_full_plus_hs38d1_analysis_set.fna
```
Where you use `--ref-fasta` to point to a GRCh38 human reference FASTA file.
