### ISSUE TITLE
vcf2maf-1.1.0 with --input-vep file setting all Hugo_Symbols to UNKNOWN

### ISSUE THREAD

**Issue by talonsensei** [mskcc/vcf2maf#281]
Inspecting the vep.vcf input file, each line has correct Ensembl gene ID assigned to the Gene field (e.g. ENSG00000171608). However when vcf2maf-1.1.0 is run with --input-vep option to use that file as input, all of the Hugo_Symbol values in the resulting maf file are set to UNKNOWN and so the maf is unusable in MAFTools. 

Any suggestions? 

I cannot run the script using --input-vcf instead, because then it crashes when running vep, even though I CAN run vep standalone and it works just fine.

**Comment by ckandoth** [comment]
Hi @talonsensei - I cannot debug such an old version. If you want to use a pre-annotated VCF, then use option `--inhibit-vep` in the most recent release.
