### ISSUE TITLE
problems with allelic frequency 

### ISSUE THREAD

**Issue by aRanghiero** [mskcc/vcf2maf#285]
Hello. I tried to convert a VCF file -version 4.1 obtained from a seq through thermo fisher- and inside the MAF file that I get I don't find information on the allelic frequency. 
I also tried to use a VCF test -test_radia- and even in that case I lose the information of the allelic frequency.
the string I used is: **perl ../vcf2maf.pl --input-vcf file.vcf --output maf file.maf --ref-fasta ../hg19.fa --vep-path /home/sunrises/miniconda3/envs/VCF2MAF/bin --tumor-id sample_name**
what am I doing wrong?
thank you

**Comment by hamrejr** [comment]
Hello,

I am having the same problem, did you ever solve this? I am using mutect2 to generate vcf's, but vcf2maf deletes the AF. Thanks!

**Comment by fyfreya** [comment]
Same here... Have you solved it?

**Comment by ckandoth** [comment]
For "variant allele fraction" i.e. the number of reads supporting the ALT allele, you need to specify either "--tumor-id" or "--tumor-vcf-id" in your command. This lets vcf2maf know which genotype column to parse in your VCF. Note that you could have a multisample VCF with many genotype field, but the MAF format only supports a tumor sample ID, and an optional normal sample ID.
