### ISSUE TITLE
Can I convert the annotated VCF file to MAF?

### ISSUE THREAD

**Issue by Zhr-Abdi** [mskcc/vcf2maf#296]
Hi,
I have a VCF file that is annotated with ANNOVAR and now I want to convert it to MAF. Can I convert it by vcf2maf?

Thanks in advance

Zahra

**Comment by ckandoth** [comment]
Annovar-annotated VCFs are unfortunately not supported by vcf2maf, because they are very different from VEP-annotated VCFs. If you can generate tab-delimited Annovar output, then you can use [annovarToMaf](https://www.rdocumentation.org/packages/maftools/versions/0.99.30/topics/annovarToMaf).
