### ISSUE TITLE
Preserve multisample genotype fields in the maf format

### ISSUE THREAD

**Issue by Biojenifer** [mskcc/vcf2maf#297]
Hi!

I am trying to transform into a MAF a VCF which includes information from 3 different samples of the same patient (tumour 1, tumour 2, normal). So this vcf has 3 different genotype fields. However, I can only indicate one --tumour-ID and one --normal-ID to `vcf2maf`. Do you know if there is some possibility to preserve the genotype information of the 3 samples?

Thanks!!

**Comment by ckandoth** [comment]
Yes, you'd run vcf2maf twice with different `--tumor-id`, and then concatenate the two MAFs together. Let me know if you need code snippets to do this.

**Comment by Biojenifer** [comment]
Thanks!
