### ISSUE TITLE
--normal-id getting passed in as value for --tumor-id intermittently

### ISSUE THREAD

**Issue by zheins** [mskcc/vcf2maf#32]
I've narrowed this down to the following section of code in maf2maf:

```perl

# For each VCF generated by maf2vcf above, contruct a vcf2maf command and run it
my @vcfs = grep{ !m/.vep.vcf$/ and !m/$vcf_file/ } glob( "$tmp_dir/*.vcf" ); # Avoid reannotating annotated VCFs
foreach my $tn_vcf ( @vcfs ) {
    my ( $tumor_id, $normal_id ) = $tn_vcf=~m/^.*\/(.*)_vs_(.*)\.vcf/;
    my $tn_maf = $tn_vcf;
    $tn_maf =~ s/.vcf$/.vep.maf/;
    my $vcf2maf_cmd = "$perl_bin $vcf2maf_path --input-vcf $tn_vcf --output-maf $tn_maf " .
        "--tumor-id $tumor_id --normal-id $normal_id --vep-path $vep_path --vep-data $vep_data " .
        "--vep-forks $vep_forks --ref-fasta $ref_fasta --ncbi-build $ncbi_build --species $species";
    $vcf2maf_cmd .= " --custom-enst $custom_enst_file" if( $custom_enst_file );
    system( $vcf2maf_cmd ) == 0 or die "\nERROR: Failed to run vcf2maf!\nCommand: $vcf2maf_cmd\n";
}

```

What seems to be happening is if $tumor_id is empty, it gets put into the command, which causes --normal-id to be set as value for --tumor-id (tested this argument/value behavior locally with another program - it simply takes whatever follows the argument as the value). 

Looking at the bad record, I also notice that what appears to be the actual Tumor_Sample_Barcode is in the Match_Normal_Seq_Allele1 column.

Here is how we are calling maf2maf in our java code:

/opt/common/CentOS_6/vcf2maf/v1.6.2/maf2maf.pl --vep-path /opt/common/CentOS_6/vep/v81 --vep-data /opt/common/CentOS_6/vep/v81 --ref-fasta
/ssd-data/cmo/opt/vep/v79/homo_sapiens/79_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa
--retain-cols
hugo_symbol,entrez_gene_id,center,ncbi_build,chromosome,start_position,end_position,strand,variant_classification,variant_type,reference_allele,tumor_seq_allele1,tumor_seq_allele2,dbsnp_rs,dbsnp_val_status,tumor_sample_barcode,matched_norm_sample_barcode,match_norm_seq_allele1,match_norm_seq_allele2,tumor_validation_allele1,tumor_validation_allele2,match_norm_validation_allele1,match_norm_validation_allele2,verification_status,validation_status,mutation_status,sequencing_phase,sequence_source,validation_method,score,bam_file,sequencer,tumor_sample_uuid,matched_norm_sample_uuid,t_depth,t_ref_count,t_alt_count,n_depth,n_ref_count,n_alt_count,high_inf_pos,motif_score_change,impact
--input-maf /data/zack/tmp/import-tmp/1448309457235.sanitizedMAF --output-maf /data/zack/tmp/import-tmp/1448309446721-0/annotator_out.maf --tmp-dir /ssd-data/vep-tmp/ben --vep-forks 32 --custom-enst /opt/common/CentOS_6/vcf2maf/v1.6.2/data/isoform_overrides_at_mskcc

We are also calling this on a "sanitized" maf, which @qwangmsk has an example of.

Would it make sense for now to place an empty check on the tumor_id and normal_id scalars for the time being to simply alert us to the data causing the issue the next time this issue comes up? We haven't been able to reproduce it, and at no other point in the java would it make sense for the --normal-id to show up in the data - this seems to be the only spot where it could potentially find its way in.

**Comment by ckandoth** [comment]
Thanks much, @zheins. I'll add `Tumor_Sample_Barcode` to the columns that must have non-empty contents. Most MAF problems are fixed on the fly, but there's no way for maf2maf to realize that the tumor ID is in the wrong column. So I'll have it poop out with an error in this case.

**Comment by ckandoth** [comment]
This thing is solved in the latest dev branch. maf2vcf/maf2maf will error out, if a variant has an undefined tumor barcode, or the barcode contain characters not allowed in Unix filenames.
