### ISSUE TITLE
I have a annotationed vep.vcf file, can I use vcf2maf to convert MAF without installing VEP? 

### ISSUE THREAD

**Issue by aaaniich** [mskcc/vcf2maf#323]
duplicate #229 , because it doesn't have answer
I have txt and html file from vep
How can I use it for vcf2maf?

**Comment by ckandoth** [comment]
From the [Quick Start](https://github.com/mskcc/vcf2maf#quick-start) documentation: `If you want to skip running VEP and need a minimalist MAF-like file listing data from the input VCF only, then use the --inhibit-vep option. If your input VCF contains VEP annotation, then vcf2maf will try to extract it. But be warned that the accuracy of your resulting MAF depends on how VEP was operated upstream. In standard operation, vcf2maf runs VEP with very specific parameters to make sure everyone produces comparable MAFs. So, it is strongly recommended to avoid --inhibit-vep unless you know what you're doing.`
