### ISSUE TITLE
Unknown option: af_esp ERROR: Failed to parse command-line flags

### ISSUE THREAD

**Issue by biginfor** [mskcc/vcf2maf#325]
Dear developer:

Something went wrong when I run vcf2maf.pl
Below are code and errors :
**CODE:**
perl ${soft}vcf2maf.pl --input-vcf ${vcfloc}CHT_LN_LT.ann.dbnsfp.vcf --output-maf ${vcfloc}maf/CHT_LN_LT.ann.dbnsfp.maf \
--tmp-dir /tmp --tumor-id CHT_LT --normal-id CHT_LN --vcf-tumor-id CHT_LT --vcf-normal-id CHT_LN --vep-path ${veploc} --vep-data \
${vepcache}  --ref-fasta ${vepcache}Homo_sapiens.GRCh37.dna.toplevel.fa
**ERROR**
STATUS: Running VEP and writing to: /tmp/CHT_LN_LT.ann.dbnsfp.vep.vcf
Unknown option: af_esp
ERROR: Failed to parse command-line flags

ERROR: Failed to run the VEP annotator! Command: /anaconda/envs/vaf2maf/bin/perl /ensembl-vep//vep --species homo_sapiens --assembly GRCh37 --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir /WES/VEP/ --fasta /VEP/Homo_sapiens.GRCh37.dna.toplevel.fa --format vcf --input_file /CHT_LN_LT.ann.dbnsfp.vcf --output_file /tmp/CHT_LN_LT.ann.dbnsfp.vep.vcf --offline --pubmed --fork 4 --polyphen b --af --af_1kg --af_esp --af_gnomad --regulatory

All files and software are based on Ensembl Release 107.

Any help would be appreciated!

**Comment by biginfor** [comment]
I edit the vcf2maf.pl Line 465 and delete the **af_esp** Now everything is ok.
$vep_cmd .= ( $vep_script =~ m/vep$/ ? " --af_1kg --af_gnomad" : " --maf_1kg --maf_esp" ) unless( $online );

**Comment by eibol1** [comment]
I had a similar error when running `vcf2maf` command. 

mskcc-vcf2maf-754d68a perl vcf2maf.pl --input-vcf ~/Desktop/training_bioinfo/VCFs_pipeline_curro/tejidos_vcfs/PCT20.filtered.vcf --output-maf ~/Desktop/PCT20.vep.maf --tumor-id PCT20T.tumor --normal-id PCT20P.normal --ref-fasta /Users/abelgd/.vep/homo_sapiens/107_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa --vep-path ~/ensembl-vep --ncbi-build GRCh38
STATUS: Running VEP and writing to: /Users/abelgd/Desktop/training_bioinfo/VCFs_pipeline_curro/tejidos_vcfs/PCT20.filtered.vep.vcf
Unknown option: af_esp
ERROR: Failed to parse command-line flags

ERROR: Failed to run the VEP annotator! Command: /Users/abelgd/perl5/perlbrew/perls/5.26.2/bin/perl /Users/abelgd/ensembl-vep/vep --species homo_sapiens --assembly GRCh38 --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir /Users/abelgd/.vep --fasta /Users/abelgd/.vep/homo_sapiens/107_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa --format vcf --input_file /Users/abelgd/Desktop/training_bioinfo/VCFs_pipeline_curro/tejidos_vcfs/PCT20.filtered.vcf --output_file /Users/abelgd/Desktop/training_bioinfo/VCFs_pipeline_curro/tejidos_vcfs/PCT20.filtered.vep.vcf --offline --pubmed --fork 4 --polyphen b --af --af_1kg --af_esp --af_gnomad --regulatory




Should I edit the line 465 from vcf2maf.pl ? Can you share the code to do that? I am kind a noob for that...

**Comment by eibol1** [comment]
> I edit the vcf2maf.pl Line 465 and delete the **af_esp** Now everything is ok. `$vep_cmd` .= `( $vep_script =~ m/vep$/ ? " --af_1kg --af_gnomad" : " --maf_1kg --maf_esp" ) unless( $online );`

Sorry I did not see this. This is the command to edit line 465 of vcf2maf.pl ? How is the correct way to proceed? 

Thank you and sorry for the inconveniences

**Comment by biginfor** [comment]
vcf2maf.pl(you can find this file in current repository) source code:
line 485 :  $vep_cmd .= ( $vep_script =~ m/vep$/ ? " --af_1kg **--af_esp** --af_gnomad" : " --maf_1kg --maf_esp" ) unless( $online );
I just delete the "--af_esp" ,now it's like this:
$vep_cmd .= ( $vep_script =~ m/vep$/ ? " --af_1kg  --af_gnomad" : " --maf_1kg --maf_esp" ) unless( $online );

**NOTE:**In fact, I don't know what other serious consequences this will have, but I haven't received any error. I hope this can help you.

**Comment by wihui** [comment]
> vcf2maf.pl(you can find this file in current repository) source code: line 485 : $vep_cmd .= ( vepscript= m/vep/ ? " --af_1kg **--af_esp** --af_gnomad" : " --maf_1kg --maf_esp" ) unless( $online ); I just delete the "--af_esp" ,now it's like this: $vep_cmd .= ( vepscript= m/vep/ ? " --af_1kg --af_gnomad" : " --maf_1kg --maf_esp" ) unless( $online );
> 
> **NOTE:**In fact, I don't know what other serious consequences this will have, but I haven't received any error. I hope this can help you.

Hi Developers,

Would there be any consequence removing the option "--af_esp"? Thank you.
