### ISSUE TITLE
fix targeted_region mutation type for inframe mutations

### ISSUE THREAD

**Issue by jjgao** [mskcc/vcf2maf#33]
Can we do the following for complex in-frame mutation?

If the var allele has more NTs than ref allele, call it a IN_FRAME_INS. If less, IN_FRAME_DEL. If equal, MISSENSE_MUTATION.

**Comment by ckandoth** [comment]
The `Consequence` column distinguishes `inframe_insertion` and `inframe_deletion`, as CLIA compliant [SO terms](http://useast.ensembl.org/info/genome/variation/predicted_data.html#consequences). If you can point me to the code that reads the MAF to generate the portal friendly alteration names, then I can edit to prefer the `Consequence` column over `Variant_Classification`, if available.

**Comment by jjgao** [comment]
We can leave `Consequence` column as is. The portal is using `Variant_Classification` column. I saw the code below in [vcf2maf.pl](https://github.com/mskcc/vcf2maf/blob/master/) to convert from `Consequence` to `Variant_Classification`.


```perl
# Converts Sequence Ontology variant types to MAF variant classifications
sub GetVariantClassification {
    my ( $effect, $var_type ) = @_;
    return "Splice_Site" if( $effect =~ /^(splice_acceptor_variant|splice_donor_variant|transcript_ablation)$/ );
    return "Nonsense_Mutation" if( $effect eq 'stop_gained' );
    return "Frame_Shift_Del" if ( $effect eq 'frameshift_variant' and $var_type eq 'DEL' );
    return "Frame_Shift_Ins" if( $effect eq 'frameshift_variant' and $var_type eq 'INS' );
    return "Nonstop_Mutation" if( $effect eq 'stop_lost' );
    return "Translation_Start_Site" if( $effect =~ /^(initiator_codon_variant|start_lost)$/ );
    return "In_Frame_Ins" if( $effect eq 'inframe_insertion' );
    return "In_Frame_Del" if( $effect eq 'inframe_deletion' );
    return "Missense_Mutation" if( $effect =~ /^(missense_variant|coding_sequence_variant|conservative_missense_variant|rare_amino_acid_variant)$/ );
    return "Intron" if ( $effect =~ /^(transcript_amplification|splice_region_variant|intron_variant|INTRAGENIC|intragenic_variant)$/ );
    return "Silent" if( $effect =~ /^(incomplete_terminal_codon_variant|synonymous_variant|stop_retained_variant|NMD_transcript_variant)$/ );
    return "RNA" if( $effect =~ /^(mature_miRNA_variant|non_coding_exon_variant|non_coding_transcript_exon_variant|non_coding_transcript_variant|nc_transcript_variant)$/ );
    return "5'UTR" if( $effect =~ /^(5_prime_UTR_variant|5_prime_UTR_premature_start_codon_gain_variant)$/ );
    return "3'UTR" if( $effect eq '3_prime_UTR_variant' );
    return "IGR" if( $effect =~ /^(TF_binding_site_variant|regulatory_region_variant|regulatory_region|intergenic_variant|intergenic_region)$/ );
    return "5'Flank" if( $effect eq 'upstream_gene_variant' );
    return "3'Flank" if ( $effect eq 'downstream_gene_variant' );

    # Annotate everything else simply as a targeted region
    # TFBS_ablation, TFBS_amplification,regulatory_region_ablation, regulatory_region_amplification,
    # feature_elongation, feature_truncation
    return "Targeted_Region";
}
```

It looks like this mapping works pretty well except for most of the mutations except for complex in-frame mutation. For example: 

http://grch37.rest.ensembl.org/vep/human/hgvs/7:g.55241678_55241681AAAC%3EG?content-type=application/json

![image](https://cloud.githubusercontent.com/assets/840895/12483897/767d8df2-c025-11e5-81ec-b564540f9840.png)

VEP call them protein_altering_variant. According to the `GetVariantClassification` above, it's mapped to `Targeted_Region` by default. (I guess that's because MAF has no proper classification for it.)

I'd like to propose to add a few lines of code between `return "Targeted_Region"; to check if the variant is an in-frame mutation by comparing the difference of ref and var alleles. If yes, map it to either 
  * IN_FRAME_INS (var allele has more NTs than ref allele), or 
  * IN_FRAME_DEL (var allele has less NTs than ref allele), or 
  * MISSENSE_MUTATION (var allele has the same NTs than ref allele -- I think this case may not happen).

**Comment by ckandoth** [comment]
Sorry this took a while, but it's now handled in the latest develop branch.

**Comment by jjgao** [comment]
@ckandoth: Great. Thanks! Could you or @qwangmsk help to update our pipeline?

**Comment by ckandoth** [comment]
No worries. I've pushed it out as a stable release alongside other features. In the pipeline, use the maf2maf located down here - /opt/common/CentOS_6-dev/vcf2maf/v1.6.5
