### ISSUE TITLE
Ensembl VEP "--regulatory" option not available for some species

### ISSUE THREAD

**Issue by brunogrande** [mskcc/vcf2maf#34]
Thanks for the recent added support for species other than humans. It's been helpful! 

I have variants called for a canine tumour dataset that I wish to annotate and convert to MAF format. However, the `--regulatory` option for Ensembl VEP isn't available for the `canis_familiaris` species, despite Ensembl not indicating that the option is "species limited" in their documentation. 

I'm fixing this by classifying that option as human-only, but you might want to include it for all supported species. Just a heads-up!

**Comment by ckandoth** [comment]
Thanks for reporting this. The wrapper in the latest dev branch now prevents using `--regulatory` with VEP, if the species is `canis_familiaris`. I will push this into the upcoming v1.6.5 release. Let me know if you find other situations like this where some VEP options fail for some species, but not others.

**Comment by brunogrande** [comment]
Thanks, Cyriac!
