### ISSUE TITLE
Release new tag

### ISSUE THREAD

**Issue by pdiakumis** [mskcc/vcf2maf#340]
Hello, thanks for this great tool.
We've been using it for years but I've noticed the latest release was in April 2021. Is it possible to release a new tag with the latest changes?
I'm specifically interested in handling the 100s of WARNINGs for unrecognised splice effects after updating VEP which was solved in mskcc/vcf2maf#320 last July.
Happy to help with the release if there is a shortage in maintenance people.

**Comment by FriederikeHanssen** [comment]
Yes this would be great :) I am running into the same thing.

**Comment by pdiakumis** [comment]
Hey @FriederikeHanssen, in case it's helpful at all, a couple weeks ago I went ahead and:

- forked this repo into https://github.com/umccr/vcf2maf
- tagged the latest main with https://github.com/umccr/vcf2maf/releases/tag/v1.6.21.20230511
- released into our teams's umccr conda channel at https://anaconda.org/umccr/vcf2maf

**Comment by ckandoth** [comment]
Thanks for this, everyone. I have merged recent PRs and made fixes related to changes in VEP args and output. See https://github.com/mskcc/vcf2maf/releases/tag/v1.6.22

There is no team at MSKCC working on vcf2maf anymore, after I quit in 2020. But I still have edit rights to the repo. Let me go through all the forks and see which one is a worthwhile replacement. Then I'll update the readme to redirect folks there.
