### ISSUE TITLE
Error Argument "" isn't numeric in subtraction

### ISSUE THREAD

**Issue by sariya** [mskcc/vcf2maf#347]
Hello,

I'm interested to use your tool in order to make MAF from an annotated consensus VCF file. I use following code:
`
perl mskcc-vcf2maf-754d68a/vcf2maf.pl --input-vcf ./annotated_variants.consensus.vcf --output-maf check.maf --ref-fasta ~/human/hg38/Homo_sapiens_assembly38.fasta.gz --vep-path ~/vep/109/src/ensembl-vep --ncbi-build GRCh38
`
I get following error:

> Argument "Entrez_Gene_Id" isn't numeric in subtraction (-) at mskcc-vcf2maf-754d68a/vcf2maf.pl line 382, <GEN2> line 210.
> Argument "" isn't numeric in subtraction (-) at mskcc-vcf2maf-754d68a/vcf2maf.pl line 382, <GEN2> line 291.
> Argument "" isn't numeric in subtraction (-) at mskcc-vcf2maf-754d68a/vcf2maf.pl line 382, <GEN2> line 327.
> Argument "" isn't numeric in subtraction (-) at mskcc-vcf2maf-754d68a/vcf2maf.pl line 382, <GEN2> line 355.
> Argument "" isn't numeric in subtraction (-) at mskcc-vcf2maf-754d68a/vcf2maf.pl line 382, <GEN2> line 391.
> [W::fai_get_val] Reference ADAL:161822-161827 not found in FASTA file, returning empty sequence
> [W::fai_get_val] Reference ADAL:161822-161827 not found in FASTA file, returning empty sequence
> 
> 

I've following output of `grep -v "#" annotated_variants.consensus.vcf   | awk '{print $1, $2,$3,$4,$5,$6}' | head`
 
> Hugo_Symbol Entrez_Gene_Id Center NCBI_Build Chromosome Start_Position
> RIMKLA 284716 __UNKNOWN__ hg38 chr1 42399471
> AK5 26289 __UNKNOWN__ hg38 chr1 77535967
> ADCY3 109 __UNKNOWN__ hg38 chr2 24834581
> PSME4 23198 __UNKNOWN__ hg38 chr2 53919178
> STARD7 56910 __UNKNOWN__ hg38 chr2 96195457
> 

samtools 1.9
perl 5, version 16

**Comment by ckandoth** [comment]
Your input file is not a VCF. You might instead want to use "maf2maf.pl" script. See the documentation by typing "perl mskcc-vcf2maf-754d68a/maf2maf.pl --help"

**Comment by sariya** [comment]
Hi, 
Thanks for your reply. When I use maf2maf.pl as

```
perl mskcc-vcf2maf-754d68a/maf2maf.pl  --input-maf  ./annotated_variants.consensus.vcf \
> --ref-fasta  /sc/human/hg38/Homo_sapiens_assembly38.fasta.gz
```

I get error:
> ERROR: MAF line 1 (at chr1:42399471) contains invalid alleles in Tumor_Seq_Allele or Match_Norm_Seq_Allele columns!
