### ISSUE TITLE
error with VEP

### ISSUE THREAD

**Issue by complexgenome** [mskcc/vcf2maf#356]
Hi,
I use following command

```
docker run -v /data1/:/data1/ --rm vcf2maf:main perl vcf2maf.pl --input-vcf /data1/users/sanjeev/docker_vcf2maf/vcf2maf/consensus.vcf --output-maf test.maf --ref-fasta /data1/users/sanjeev/docker_vcf2maf/vcf2maf/GRCh38.primary_assembly.genome.fa --vep-path /data1/software/ensembl-vep/   --vep-data  /data1/software/vep_cache/  --tmp-dir  /data1/users/sanjeev/docker_vcf2maf/vcf2maf/   --vcf-tumor-id tumor --vcf-normal-id normal
```

I run into error as:

> ERROR: Failed to run the VEP annotator! Command: /usr/local/bin/perl '/data1/software/ensembl-vep//vep' --species homo_sapiens --assembly GRCh37 --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir '/data1/software/vep_cache/' --fasta '/data1/users/sanjeev/docker_vcf2maf/vcf2maf/GRCh38.primary_assembly.genome.fa' --format vcf --input_file '/data1/users/sanjeev/docker_vcf2maf/vcf2maf/consensus.vcf' --output_file '/data1/users/sanjeev/docker_vcf2maf/vcf2maf//consensus.vep.vcf' --offline --pubmed --fork 4 --polyphen b --af --af_1kg --af_gnomad --regulatory

Of course the build are different. I do not know how to tell vcf2maf for the build, as it doesn't accept VEP arguments.

**Comment by ckandoth** [comment]
Reads the manual using `docker run --rm vcf2maf:main perl vcf2maf.pl --man` and look up arg `--ncbi-build`.
