### ISSUE TITLE
ExAC DNPs

### ISSUE THREAD

**Issue by alexpenson** [mskcc/vcf2maf#37]
DNPs composed of two ExAC SNPs are not annotated.

Solution: add these DNPs (and TNPs?) to the vcf.

**Comment by alexpenson** [comment]
chr22:29091840-29091841:TG:CA
CHEK2
p.K416E

**Comment by alexpenson** [comment]
Also: http://exac.broadinstitute.org/region/6-41903782-41903782

**Comment by ckandoth** [comment]
Sample VCF where 1000g, NHLBI EVS, and ExAC allele freqs are only provided for the SNPs, but not for the DNP:

```bash
##fileformat=VCFv4.2
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=G,Type=Integer,Description="Allelic Depths of REF and ALT(s) in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR	NORMAL
6	41903782	.	A	C	.	.	.	GT:AD:DP	0/1:10,10:20	0/0:22,0:22
6	41903783	.	G	A	.	.	.	GT:AD:DP	0/1:11,10:21	0/0:21,1:22
6	41903782	.	AG	CA	.	.	.	GT:AD:DP	0/1:10,10:20	0/0:21,0:21
```

**Comment by ckandoth** [comment]
I figure I could make this part of [this gist](https://gist.github.com/ckandoth/f265ea7c59a880e28b1e533a6e935697) for VEP installation, where I already require the user to edit the ExAC VCF with bcftools. `bcftools concat` has a feature to `--ligate` phased VCFs by matching overlapping haplotypes... which would have been perfect iff everyone reported phased VCFs. 🙄

Really, we just need a simple script that merges adjacent ExAC SNPs with similar allele-counts. The ExAC VCF is already sorted by position. So a one-liner is possible.

**Comment by ckandoth** [comment]
I just figured out VEP's internal solution when reporting allele freqs from 1000g, ESP, or ExAC. They apparently report the freq of all non-reference alleles at the given `POS`, without trying to match the variant allele to the input. So in the above example, the DNP at position `41903782` would get assigned the allele freq of SNPs and/or indels at the same position. This would include the allele freq of the SNP at position 41903782.

**Comment by ckandoth** [comment]
Just hit a bottleneck. [`6-41903782-A-C`](http://exac.broadinstitute.org/variant/6-41903782-A-C) has `AC=65104`, and [`6-41903783-G-A`](http://exac.broadinstitute.org/variant/6-41903783-G-A) has `AC=5264`. And they are found in phase only in `2432` individuals. This phased ACs are only reported in the ExAC web pages, and is not in their downloadable VCF. Ideally, a future release will list multiallelic loci with separate allele counts for SNPs and MNPs. But right now, we just don't have the correct ACs for DNPs or MNPs.

So as a workaround, I will report the sum of ACs of all non-reference alleles at a given position, even if it doesn't match the input allele. Same as explained in my last comment here. So for an input of `6-41903782-AG-CA`, the allele count reported will be the sum of ACs of [`6-41903782-A-C`](http://exac.broadinstitute.org/variant/6-41903782-A-C) and [`6-41903782-A-T`](http://exac.broadinstitute.org/variant/6-41903782-A-T)

**Comment by ckandoth** [comment]
This is now handled in 86e58e3
