### ISSUE TITLE
entrez identifiers

### ISSUE THREAD

**Issue by aderidder** [mskcc/vcf2maf#39]
Hi,

After running vcf2maf all the Entrez_Gene_Id values are set to '0'. Would it be possible to add the entrez identifiers?

Best regards,
Sander

**Comment by ckandoth** [comment]
Entrez IDs are from this side of the pond, and map uniquely to NCBI Refseq genes. While VEP is a product of EMBL-EBI, with better support for Gencode genes. VEP can also annotate variants using Refseq genes and Entrez IDs, but the mapping of those to Gencode is ambiguous. Moreover, Refseq genes are mostly a subset of what's in Gencode. This is why I decided to keep vcf2maf limited to Gencode transcripts. The downside is a lack of unambiguous Entrez IDs MAF column 2. IMHO, Entrez gene IDs should never have been included in the MAF specs. Transcript IDs would have been infinitely better.

Lots of folks have asked for this though. So I am thinking of workarounds. I have a helper script that uses the [eutils web service](http://www.ncbi.nlm.nih.gov/books/NBK25500/#chapter1.Searching_a_Database) to backfill entrez IDs in a given MAF, but I don't want to add a slow web-service dependency to vcf2maf. Ideally, I would get the Entrez IDs directly from VEP.

**Comment by aderidder** [comment]
Hi, thanks for explaining. 
I had never even heard of eutils web services, so I'll definitely check that out.

**Comment by kmhernan** [comment]
hah I am having this exact issue and agree with your sentiments. I wrote a VEP plugin for this that uses a JSON file to do the mapping, but it still doesn't get around the ambiguous mapping of Gencode transcript IDs to Entrez IDs. Curious to know if you figure out a better way.

**Comment by jjgao** [comment]
Hi @ckandoth any update on this? Would you prioritize? Thanks!

**Comment by ckandoth** [comment]
@jjgao I went ahead with the workaround you suggested - downloaded an ENSG to Entrez ID mapping, and dumped it into the repo. If found, it will be used by `vcf2maf` to add Entrez IDs. If ambiguous, or not found, the Entrez ID will remain at `0`. Implemented in 25962c4. I want to incorporate this into release `v1.7`, which might take me a week longer. Ping me over GChat if If you want this ASAP in production - then I'll release a `v1.6.9` instead, which simply adds this feature.

**Comment by pieterlukasse** [comment]
This is great news! Looking forward to see the improved mutation MAF files later in https://github.com/cBioPortal/datahub. Maybe a follow-up PR after https://github.com/cBioPortal/datahub/pull/3

**Comment by ckandoth** [comment]
Note: to generate this [ENSG to Entrez ID mapping](https://github.com/mskcc/vcf2maf/blob/v1.6.14/data/ensg_to_entrez_id_map_ensembl_feb2014.tsv), I used Ensembl's Biomart from their Feb 2014 archive - http://feb2014.archive.ensembl.org/biomart/martview - because this archived version is what we all are stuck with, as long as we're doing GRCh37 annotation.
