### ISSUE TITLE
t_ref_count, t_alt_count, n_ref_count, n_alt_count not printing out in annotated maf

### ISSUE THREAD

**Issue by kk988** [mskcc/vcf2maf#41]
I'm having trouble trying to get t_ref_count, t_alt_count, n_ref_count, n_alt_count to print out in the maf with the v1.6.5 of maf2maf.pl using a dataset that worked with a previous version of the script.

Thanks,
Krista

**Comment by lordzappo** [comment]
We should snag this file for a test suite cyriac

**Comment by ckandoth** [comment]
Thanks for reporting this. I pushed a fix to master and develop branches, and a v1.6.6 will be released as soon as we set up proper unit testing in #28
