### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by kmhernan** [mskcc/vcf2maf#42]
I just noticed this. On ~ line [359](https://github.com/mskcc/vcf2maf/blob/master/vcf2maf.pl#L359)

Currently:

```
$tum_info{GT} = "./." unless( defined $tum_info{GT} and $tum_info{GT} ne '.' );
```

Should it not be:

```
$nrm_info{GT} = "./." unless( defined $nrm_info{GT} and $nrm_info{GT} ne '.' );
```

**Comment by ckandoth** [comment]
Thanks for reporting this. I've pushed a fix in the latest master branch. Will push to a new 1.6.6 as soon as I set up proper unit testing.
