### ISSUE TITLE
sequence_feature missing in vcf2maf

### ISSUE THREAD

**Issue by apastore** [mskcc/vcf2maf#43]
Hi Cyriac,
running vcf2maf 1.6.6 with vep83 i am getting:
ERROR: Unrecognized effect "sequence_feature". Please update your hashes!

I have add sequence_feature to vcf2maf feature but i just want to ask you if that is correct.

Thanks!

**Comment by apastore** [comment]
I have the same issues with protein_protein_contact

**Comment by ckandoth** [comment]
Sorry for the late reply. I will release vcf2maf v1.7 within the next few days that will no longer override VEP's prioritization of effects. So these hashes with custom effect rankings will go away.

**Comment by apastore** [comment]
thanks!

**Comment by ckandoth** [comment]
This is handled now in v1.6.7 that was just released. v1.7 is backlogged because the VEP way of prioritizing effects needs more testing.
