### ISSUE TITLE
MAF file input

### ISSUE THREAD

**Issue by ksw9** [mskcc/vcf2maf#45]
Hi,
I am trying to use your maf2maf.pl script to convert an MAF file I generated with the MUGSY aligner (http://mugsy.sourceforge.net/) into a VCF file format.  

Is your script for MAFs in a specific format?  I run into the error: 
ERROR: Couldn't find a header line (starts with Hugo_Symbol, Chromosome, or Tumor_Sample_Barcode) in the MAF: outgroup.maf

Thank you!

The first few lines of my MAF:

##maf version=1 scoring=mugsy
a score=640492 label=1 mult=3
s B31.Chromosome                4603 638466 + 910724 AAAATCTCAGGAGAGGGATCAAATGGGGGATGCATAATTCATCCTTCAAGGGTAAGAGACCCAATTACTACTTTACTTAGTATCGTAAAATTATTAAAAATGAA

**Comment by ckandoth** [comment]
Looks like you're trying to convert [Multiple Alignment Format](https://genome.ucsc.edu/FAQ/FAQformat.html#format5), which is different from [Mutation Annotation Format](https://wiki.nci.nih.gov/x/eJaPAQ), that maf2vcf expects.
