### ISSUE TITLE
vcf to maf conversion

### ISSUE THREAD

**Issue by raman91** [mskcc/vcf2maf#47]
Hi, i used vcf2maf perl script. Installed vcf2maf-master, vep. But getting an error - WARNING: Chromosome 1 not found in cache on line . What can be the reason?

**Comment by ckandoth** [comment]
Can you give me a sample of the VCF that produces this error?

**Comment by raman91** [comment]
I am working on the example file (test.vcf)

File : 

##fileformat=VCFv4.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	881752	rs35372813	CA	C	.	PASS	.
1	898120	rs142704607	G	A	.	PASS	.
1	899427	rs368133518	C	T	.	PASS	.
1	935087	rs370586563	G	A	.	PASS	.
1	981235	rs373631709	G	T	.	PASS	.
1	981523	rs374079858	C	G	.	PASS	.
1	985465	rs200384052	G	A	.	PASS	.
1	989295	rs369308183	C	T	.	PASS	.
1	1019470	rs201542151	G	A	.	PASS	.
1	1139830	.	GCA	G	.	PASS	.
1	1222363	rs370083075	T	G	.	PASS	.
1	1231565	rs367638759	G	A	.	PASS	.
1	1233502	rs367866929	G	A	.	PASS	.
1	1263113	rs368308225	C	T	.	PASS	.
1	1275628	rs148469831	C	T	.	PASS	.
1	1290664	rs142988174	G	C	.	PASS	.
1	1322765	rs201055911	C	T	.	PASS	.
1	1334471	rs141133034	G	A	.	PASS	.
1	1374752	rs201042102	C	T	.	PASS	.
1	1500315	.	GAA	G	.	PASS	.
1	1559312	rs372178622	G	A	.	PASS	.

**Comment by ckandoth** [comment]
I'm unable to reproduce this bug. Did you produce/edit the VCF manually, or was it generated by a variant caller?

**Comment by raman91** [comment]
No, it was generated using a variant caller

**Comment by ckandoth** [comment]
Can you upload a test VCF somewhere that I can download it from? I lose all the tabs and formatting when you copy paste it into github

**Comment by raman91** [comment]
Hi,

Please find attached the test vcf file

Thanks

Regards
Raman

**Comment by raman91** [comment]
https://drive.google.com/file/d/0B7ZRdUypEqvRZVkxSEMySkFpeTg/view?usp=sharing

**Comment by ckandoth** [comment]
Thanks for uploading this, Raman. I ran vcf2maf as follows and it ran successfully:
```bash
perl vcf2maf.pl --input-vcf test.vcf --output-maf test.vep.maf
```
Did you follow the complete instructions to install VEP with it's offline cache, as mentioned in the readme? To be sure, check that the following file exists:
```bash
~/.vep/homo_sapiens/83_GRCh37/info.txt
~/.vep/homo_sapiens/83_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz
```

**Comment by raman91** [comment]
Yes, i installed it using the instructions given in the manual. 
The problem got solved. Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz file was not in the folder. But now there is another error : Use of unitialized value in list assignment at vcf2maf.pl line 166, <GEN0> line104.

Thanks

Regards
Raman

**Comment by ckandoth** [comment]
That's a warning message, that usually results in some missing values in the final MAF. If that is a new problem, please open a new issue at https://github.com/mskcc/vcf2maf/issues
