### ISSUE TITLE
running vcf2maf with VEP installed as module

### ISSUE THREAD

**Issue by jpreston555** [mskcc/vcf2maf#48]
Hello,

I am trying to run vcf2maf on a university computer cluster that has VEP installed as a module. When I try to run vcf2maf, I get the error "ERROR: Cannot find VEP script variant_effect_predictor.pl in path:"

I saw in the manual that it is possible to tell vcf2maf where the vep perl script is installed but in this case there is no location as it is a module.

Is there any way to run vcf2maf like this?

Thanks!!

**Comment by jpreston555** [comment]
Nevermind, we got it to work.

**Comment by gaom001** [comment]
I got the same issue, how to make it work?  Thx

**Comment by xshah** [comment]
was someone able to find a solution for this?
