### ISSUE TITLE
vcf2maf with mouse genome?

### ISSUE THREAD

**Issue by jpreston555** [mskcc/vcf2maf#49]
Hi,

Is it possible to use vcf2maf using mouse genome? When I try to run, it says: 

ERROR: Reference FASTA not found: /home/.vep/homo_sapiens/83_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz

The vep program seems to have put the mouse genome in this location already. Is there any option to specify mouse? 

[~/ .vep]$ ls
mus_musculus  mus_musculus_vep_82_GRCm38.tar.gz  variant_effect_output.txt  variant_effect_output.txt_summary.html

Thanks a lot!

**Comment by ckandoth** [comment]
Run vcf2maf with `--help` or `--man` to learn all the options. There's one called `--ref-fasta` to point it to the mouse reference. If you followed my instructions on installing VEP, then it should be at `mus_musculus/83_GRCm38/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz`
