### ISSUE TITLE
vcf2maf problem - regulatory is not available for this species

### ISSUE THREAD

**Issue by xiaxuyang** [mskcc/vcf2maf#51]
Hi,I get a problem when I use vcf2maf perl script, and I don't know how to solve it.Can you help me?Thanks!

ERROR: --regulatory is not available for this species at /home/xiaxy/vep/variant_effect_predictor.pl line 878.
ERROR: Failed to run the VEP annotator!

**Comment by ckandoth** [comment]
Are you trying to annotate variants from a non-human species? If you let me know which one, I'd code in an exception.

**Comment by xiaxuyang** [comment]
No.I'm just trying to annotate variants from a human species.And I get the same problem when I use your test.vcf .

**Comment by ckandoth** [comment]
Can you give me the full command you're trying to run?

**Comment by xiaxuyang** [comment]
vcf2maf.pl --input-vcf  /home/xiaxy/practice/varscan/snp-indel1.vcf  --output-maf /home/xiaxy/practice/vcf2maf/snp-indel1.maf  --tumor-id WD1000 --normal-id NB1001 
The version of vcf2maf is 2.0

**Comment by ckandoth** [comment]
Can you confirm the vcf2maf version? The latest is 1.6.6

**Comment by xiaxuyang** [comment]
Apologized for the misunderstood, our administrator installed the software months ago and I could not find the version information, is there any possible to get version number from the vcf2maf program.

**Comment by ckandoth** [comment]
No, there's no easy way to figure out the version. You can look at the "Last modified" date of the vcf2maf.pl program, and see which one of these releases it is closest to - https://github.com/mskcc/vcf2maf/releases

**Comment by ckandoth** [comment]
It is most likely that your admin has installed VEP in a different way than explained in the vcf2maf instructions. Ideally, you should contact your admin to help troubleshoot.

If that is not possible, then you should follow my instructions to install VEP, so that I can help troubleshoot - https://gist.github.com/ckandoth/9d6ad6a7fd3b058e5bc98a1ce884641a

**Comment by xiaxuyang** [comment]
In fact, I did nothing, the problem has been solved. I get a new problem.
By the way, I can run successfully using your test.vcf .
[wrong_information.txt](https://github.com/mskcc/vcf2maf/files/256784/wrong_information.txt)

**Comment by ckandoth** [comment]
Please submit the new problem as a new issue. And provide the full command you tried to run.
