### ISSUE TITLE
Forked process(es) died

### ISSUE THREAD

**Issue by xiaxuyang** [mskcc/vcf2maf#52]
Hi.I get a new problem. 
Command line: /software/vcf2maf/vcf2maf.pl --input-vcf ./mm.vcf --output-maf ./mm.maf --tumor-id WD1000 --normal-id NB1001
By the way,I can run successfully using your test.vcf .
[wrong_information.txt](https://github.com/mskcc/vcf2maf/files/258483/wrong_information.txt)

**Comment by ckandoth** [comment]
Please rerun that with this additional argument `--vep-forks 1`, and let me know what happens. This forces VEP to avoid using forks for parallelization, so it will hopefully produce a better error message.

**Comment by xiaxuyang** [comment]
I can run with my snp.vcf but indel.vcf.Is this format of indel.vcf wrong ?
[wrong.txt](https://github.com/mskcc/vcf2maf/files/276166/wrong.txt)

**Comment by ckandoth** [comment]
Thanks for that error log, and sorry for the late reply. It looks like `varscan2.indel.vcf` has some unusual newline characters. Make sure that it's simple unix newlines, remove all those blank lines, and try again.

**Comment by ckandoth** [comment]
I'm going to assume you got this fixed, can resolve this issue.
