### ISSUE TITLE
On-line server tools?

### ISSUE THREAD

**Issue by Puriney** [mskcc/vcf2maf#54]
Do you have any idea to setup this as on-line server tool? For example, place under cBioPortal?

**Comment by ckandoth** [comment]
`vcf2maf` is simply a wrapper around VEP, which is available as a web-service - https://rest.ensembl.org/#VEP. The only reason that `vcf2maf` exists, is because VEP does not produce annotations in MAF format - a format that I would love to see obsoleted. What is the use-case you had in mind?

**Comment by Puriney** [comment]
I like `vcf2maf` very much but I need to install VEP on my server as well. Just out of curiosity for asking the plan.

Many thanks for developing `vcf2maf`.
