### ISSUE TITLE
Problems installing VEP v84

### ISSUE THREAD

**Issue by Mandy-16** [mskcc/vcf2maf#55]
Dear all,

I am trying to install vcf2maf in Mac Os x 10.9.5.
I followed the instructions, but I got the following error message during the installation of VEP v84:

ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/HTS.bs')
env MACOSX_DEPLOYMENT_TARGET=10.3 cc -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib -fstack-protector -o blib/arch/auto/Bio/DB/HTS/HTS.bundle lib/Bio/DB/HTS.o -L/User/vep/v84/htslib -Wl,-rpath,/User/vep/v84/htslib -lhts -lpthread -lz
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error building blib/arch/auto/Bio/DB/HTS/HTS.bundle from lib/Bio/DB/HTS.o at /User/perl5/perlbrew/perls/perl-5.22.0/lib/5.22.0/ExtUtils/CBuilder/Base.pm line 320.
ERROR: Shared Bio::DB:HTS library not found

Best regards,

**Comment by ckandoth** [comment]
Sorry for the delayed reply. I have tested those steps on various Linux distributions, but never on OSX. But there have been others who told me they got it to work after installing other dependencies. Have you installed all the developer tools for OSX? `Xcode`, `homebrew` or `macports`?

**Comment by ckandoth** [comment]
I've also experienced weird errors [like this](http://lists.ensembl.org/pipermail/dev/2014-October/010492.html) with perlbrew, which I spent days to troubleshoot, all in vain. I would recommend a local install as explained in [this gist](https://gist.github.com/ckandoth/c16b9a423b54dc0a7a37).

**Comment by ckandoth** [comment]
I'm going to assume this issue is resolved. Please reopen if not.

**Comment by ispadoto** [comment]
Hi ckandoth! I used your gist to install perls but I got the same error. :(

**Comment by ckandoth** [comment]
@ispadoto note that this thread is outdated. There is a new gist available for v86. Please try that and let me know if you have issues. It is important that you open q new thread with new into on your specific problem. Or it's very difficult to troubleshoot anything.
