### ISSUE TITLE
_sice

### ISSUE THREAD

**Issue by alexpenson** [mskcc/vcf2maf#56]
really?

**Comment by lordzappo** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9788566-132012173_2-s1-v1.png?palette=1&width=246)

**Comment by alexpenson** [comment]
Yes perhaps I should have been more secific: the output of maf2maf often has HGVSp_Short set to sintering like "X200_sice", which should be _splice. Presumably a typo, but it's been around for a while

**Comment by ckandoth** [comment]
There is only this one spot that appends `_splice` - https://github.com/mskcc/vcf2maf/blob/master/vcf2maf.pl#L441 - and it looks kosher. Can you gimme an example to reproduce this? Could it be some parsing code you're using downstream that is trying to remove the `p` that precedes HGVSp notation?
