### ISSUE TITLE
ERROR: Unrecognized biotype "lncRNA". Please update your hashes!

### ISSUE THREAD

**Issue by hongenxu** [mskcc/vcf2maf#57]
Hi, 
I used vcf2maf for chicken genome and got errors "Unrecognized biotype "lncRNA". Please update your hashes!". I am not sure this problem is due to vcf2maf or my custom built VEP database. First I try to ask here. 
My command for VCF2MAF was
`perl ${vcf2maf} --input-vcf ${vcf}  --output-maf ${maf} \
                --species gallus_gallus \
                --vep-path  ${vep_path} \
                --ref-fasta ${ref}\
                --ncbi-build 84 \
                --tumor-id  842-2_S20\
                --normal-id 842-0_2_S28`
My command for building VEP database was 

`perl gtf2vep.pl -i genes.gff -f galgal5_seq.fa -d 84 -s gallus_gallus`

Thanks in advance. 

Hongen

**Comment by ckandoth** [comment]
The correct sequence ontology (SO) term is `lincRNA` not `lncRNA`. The biotypes supported by vcf2maf are [listed here](https://github.com/mskcc/vcf2maf/blob/master/vcf2maf.pl#L91). Can you give some more information on your custom VEP database, and why you had to customize it?

**Comment by ckandoth** [comment]
Btw, here is a more official list of biotypes that VEP outputs - http://useast.ensembl.org/info/genome/variation/predicted_data.html#consequences - I wouldn't recommend deviating from it, unless you had a good reason to customize. Lemme know. I'll be glad to find an easier solution to your original problem.

**Comment by hongenxu** [comment]
Hi Dr. Kandoth,

thanks a lot for your help. We are analyzing chicken tumor NGS data. We used chicken genome version galgal5, which is not supported by ensembl (and VEP) now. So I built VEP database from GFF file downloaded from NCBI

`ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000002315.4_Gallus_gallus-5.0/GCF_000002315.4_Gallus_gallus-5.0_genomic.gff.gz`

the gff file is actually gff3, and I checked with vep's gtf2vep.pl, it seems to me that It only work with gff2. NCBI seems to use kind of different  sequence ontology (SO) terms with GENCODE. 

I tried to convert gff3 to gff2 or gtf, but used those gff2 or gtf files to build VEP database, then vcf2maf gave me errors with Unrecognized biotype "lncRNA", "telomerase_RNA", "precursor_RNA", or "SRP_RNA".

Do I need to change biotypes of GFF file I have or do you have other suggestions?

thanks.

Best regards,
Hongen

**Comment by ckandoth** [comment]
Ensembl is usually good about importing assemblies and GTFs from NCBI and formatting them in a way that works well with VEP. Have you tried using the GTFs that live here - `ftp://ftp.ensembl.org/pub/release-84/gtf/gallus_gallus/`. At first glance, it looks like an older version than you're trying to use. Is this correct?

**Comment by ckandoth** [comment]
Also, please try to use vcf2maf v1.6.7 - https://github.com/mskcc/vcf2maf/releases/tag/v1.6.7 - where "Unrecognized effect/biotype will now receive lowest priority, instead of failing with an error". You can see the full list of effects in a column called `all_effects`

**Comment by hongenxu** [comment]
Hi,

thanks for your reply. GTF files in ftp://ftp.ensembl.org/pub/release-84/gtf/gallus_gallus/ are for galgal4. We are working with galgal5. Thanks for the new version, and I will get back to this issue. 

Thanks,
Hongen

**Comment by hongenxu** [comment]
vcf2maf v1.6.7 solved the problem. Sorry for not noticing the newest version. Thanks for your help.

**Comment by ckandoth** [comment]
great, glad to hear.
