### ISSUE TITLE
Reference allele does not match Ensembl reference

### ISSUE THREAD

**Issue by thomasyu888** [mskcc/vcf2maf#58]
Hey,

Thank you in advance for your time. When I run maf2maf, I get these warnings/messages.  It is able to run all the way through, but the 64 warnings I get cut my final maf file short.  I read [this issue](https://github.com/mskcc/vcf2maf/issues/38), so is there currently no way around this? I am using the most up to date vcf2maf and also vep v84.  It says on [here](https://github.com/mskcc/vcf2maf#maf2maf) that Tumor_seq_allele1 is not required, so can I ignore the first ~1000 messages? 
```
Use of uninitialized value $col_idx{"tumor_seq_allele1"} in pattern match (m//) at /home/vcf2maf/maf2vcf.pl line 120, <GEN0> line 1082.
Use of uninitialized value $col_idx{"tumor_seq_allele1"} in pattern match (m//) at /home/vcf2maf/maf2vcf.pl line 120, <GEN0> line 1083.
Use of uninitialized value $col_idx{"tumor_seq_allele1"} in pattern match (m//) at /home/vcf2maf/maf2vcf.pl line 120, <GEN0> line 1084.
Use of uninitialized value $col_idx{"tumor_seq_allele1"} in pattern match (m//) at /home/vcf2maf/maf2vcf.pl line 120, <GEN0> line 1085.

WARNING: Specified reference allele TGT does not match Ensembl reference allele GTT on line 8
WARNING: Specified reference allele CTTGATGTA does not match Ensembl reference allele TTGATGTAC on line 9
WARNING: Specified reference allele GAATTAAGA does not match Ensembl reference allele TAAGAGAAG on line 29
WARNING: Specified reference allele CAA does not match Ensembl reference allele aac on line 42
WARNING: Specified reference allele TG does not match Ensembl reference allele GT on line 51
WARNING: Specified reference allele CG does not match Ensembl reference allele GA on line 56
```

Best,
Tom

**Comment by ckandoth** [comment]
Sorry for the late response. Can you confirm that you're using v1.6.7? The `uninitialized value` message doesn't correspond to line 120 in `maf2vcf.pl`.

Regd the mismatched reference allele warnings, the problem is that some or all of your indels are using the VCF-style prefixed bp. This should also be handled by the latest v1.6.7, but there may be exceptions, where it doesn't get handled right. If you give me a sample of your input file, I can troubleshoot.

**Comment by thomasyu888** [comment]
Thank you for your response.  I will look into this and let you know when I have the answers. 

Best,
Tom

**Comment by thomasyu888** [comment]
Apologies, I had uploaded the wrong log file, there is no longer the uninitialized error.  However, I still have about 64 warnings. 

```
WARNING: Specified reference allele TGT does not match Ensembl reference allele GTT on line 8
WARNING: Specified reference allele CTTGATGTA does not match Ensembl reference allele TTGATGTAC on line 9
WARNING: Specified reference allele GAATTAAGA does not match Ensembl reference allele TAAGAGAAG on line 28
WARNING: Specified reference allele CAA does not match Ensembl reference allele aac on line 41
```

The command is:
```
perl ~/software/vcf2maf/maf2maf.pl --input-maf myMAF.maf --output-maf out.maf --vep-path vep/ --vep-data ~/.vep/ --custom-enst vcf2maf/data/isoform_overrides_at_mskcc --ref-fasta reference/hg19/hg_19_all_chrs.fasta
```
This is a line that produces that error:  Unforunately, I'm not certain how to find the exact lines that are causing this error:
```
Hugo_Symbol     Chromosome      Center  Start_Position  Reference_Allele        Tumor_Seq_Allele2       Tumor_Sample_Barcode
AKT1    chr14           105246540       TCTTGATGTA      T       test
```

**Comment by ckandoth** [comment]
Thanks Tom. Notice how both reference and variant alleles have a preceding `T`. That is VCF format, not MAF. In a MAF file, this deletion would look like this:

    chr14    105246541    CTTGATGTA    -

**Comment by thomasyu888** [comment]
Thanks for the quick response.  Is it likely that my entire maf file is in VCF format?  Should I be removing the first allele for both `Reference_Allele` and `Tumor_Seq_Allele2`, or would it just be the specific 63 cases?  

Best
Tom

**Comment by thomasyu888** [comment]
Thank you for the response and your time.  I played around with the formatting a bit and just like you said, for indels you have to remove repeats.  So things like `CCA    CA` would be `CA    -`, and `C    CCA`  would be `-    CA`. 

However, after replacing all those lines with this occurrence, I am still getting warnings:  These are some of the lines: (It did reduce the number of warnings to 29)

```
chr7	55242464	AGGAATTAAGAGAAGCAAC	A
#Replaced with
chr7	55242464	GGAATTAAGAGAAGCAAC	-
#Gives Error
WARNING: Specified reference allele GGAATTAAGAGAAGCAAC does not match Ensembl reference allele AGGAATTAAGAGAAGCAA on line 484
```

**Comment by ckandoth** [comment]
Tom, you might be doing more than is needed. Is there a reason you want to use `maf2maf` over `vcf2maf`? Both genomic loci and alleles need to be modified, when converting from VCF to MAF format... and it's non-trivial, especially for complex indels. This is one of the motivations behind my `vcf2maf` tool.

It look like your input file is more like a VCF than a MAF. So I would recommend leaving it as is, and then using `vcf2maf`.

**Comment by ckandoth** [comment]
I suspect there is a step upstream of your `myMAF.maf` file, where it used to be a VCF. If that's the case, then you can use `vcf2maf` and save yourself the trouble of turning this into a proper MAF.

**Comment by thomasyu888** [comment]
Apologies for the delay in response.  Thank you so much for your help.  The reason I am using maf2maf is because the format of mutation calls that is given to me has columns:
```
Hugo_Symbol     Chromosome      Center  Start_Position  Reference_Allele        Tumor_Seq_Allele2       Tumor_Sample_Barcode
```
Could I potentially run vcf2maf without the other columns and the vcf headers?
```
CHROM POS ID REF ALT QUAL FILTER INFO FORMAT ...
```

**Comment by ckandoth** [comment]
I took a closer look at these 2 variants you sent:
```
Chromosome  Start_Position  Reference_Allele     Tumor_Seq_Allele2  Tumor_Sample_Barcode
14          105246540       TCTTGATGTA           T                  sample_blah
7           55242464        AGGAATTAAGAGAAGCAAC  A                  sample_bleh
```
The first one has a `Start_Position` that is 1bp more than it should be. While the second one seems accurate. So the following input actually works fine in `maf2maf`:
```
Chromosome  Start_Position  Reference_Allele     Tumor_Seq_Allele2  Tumor_Sample_Barcode
14          105246539       TCTTGATGTA           T                  sample_blah
7           55242464        AGGAATTAAGAGAAGCAAC  A                  sample_bleh
```
`maf2maf` will remove the VCF-style prefixed bps, increment the `Start_Position` and generate a properly formatted MAF like this:
```
Chromosome  Start_Position  Reference_Allele     Tumor_Seq_Allele2  Tumor_Sample_Barcode
14          105246540       CTTGATGTA            -                  sample_blah
7           55242465        GGAATTAAGAGAAGCAAC   -                  sample_bleh
```

Whoever gave you these mutation calls, needs to explain how they generated it. Hopefully that tells you which variants have an incorrect `Start_Position` that you need to modify.

**Comment by thomasyu888** [comment]
I will ask and find out which variants have an incorrect `Start_Position` so that I can correctly parse these files.  Thank you for all of your help.
