### ISSUE TITLE
maf2.4 is not suite for MuSic0.4

### ISSUE THREAD

**Issue by sun010848** [mskcc/vcf2maf#59]
Hi,
my vcf file was annotated by VEP(version 84)
and transfrom vep.vcf to maf( TCGA MAF Specification v2.4) file using vcf2maf(latest version)
But during running Genome music0.4 code:

```
genome music bmr calc-covg --roi-file ../ensembl_67_cds_ncrna_and_splice_sites_hg19 --bam-list bam.list --output-dir MusiC/test --reference-sequence ../human_g1k_v37.fasta --gene-covg-dir MusiC/test/gene-covg-dir
genome music bmr calc-bmr --roi-file ../ensembl_67_cds_ncrna_and_splice_sites_hg19 --bam-list bam.list --output-dir MusiC/test --reference-sequence ../human_g1k_v37.fasta --maf-file test.vep.maf  --bmr-output MusiC/test --gene-mr-file MusiC/test/test.gene-mr-file
```

there were some error,like:

> Unrecognized Variant_Classification Splice_Region in MAF file.
> Please use TCGA MAF Specification v2.3.

maybe music0.4 is not support maf 2.4, how could I fix this error?
thanks
xq

**Comment by ckandoth** [comment]
Hi xq. `Splice_Region` is not a valid `Variant_Classification` in MAF specs, but it was added to vcf2maf out of necessity. It is difficult to predict the effect of mutations at or near splice junctions, as [explained here](https://github.com/mskcc/vcf2maf/issues/63#issuecomment-236981452). If you just want to get MuSiC working, I recommend renaming `Splice_Region` events to `Splice_Site` events.
