### ISSUE TITLE
Add trinuc context as extra MAF column

### ISSUE THREAD

**Issue by ckandoth** [mskcc/vcf2maf#61]
Add trinuc context as an extra column output to maf2maf/vcf2maf.

Here is code in maf2vcf to locate samtools binary:
https://github.com/mskcc/vcf2maf/blob/master/maf2vcf.pl#L16

Samtools faidx can be used to grab ref fasta seq for a given chr:start-stop
https://github.com/mskcc/vcf2maf/blob/master/maf2vcf.pl#L167

**Comment by ckandoth** [comment]
@adamabeshouse Will try to get to this mid next week.

**Comment by adamabeshouse** [comment]
@ckandoth Did you get a chance to look at this yet?

**Comment by ckandoth** [comment]
Nope. Not yet. I'll find time this weekend.

**Comment by ckandoth** [comment]
Implemented in c02689fb4ceaeb485d374024e336e08bbf8caa3c. If you use the CMO Haystack tools, you can access it with `cmo_vcf2maf --version develop`. If you don't use them, then start using them, by adding `/opt/common/CentOS_6-dev/python/python-2.7.10/bin` to your `$PATH`. I have a bunch more issues to address before I release a stable `v1.6.8`.
