### ISSUE TITLE
All Hugo symbols are Unknown

### ISSUE THREAD

**Issue by giftig108** [mskcc/vcf2maf#62]
Hello,

after running vcf2maf with provided test file I get 'Unknown' Hugo symbol for all variants and also many other fields like  Reference_Allele, Tumor_Seq_Allele1,  Tumor_Seq_Allele2,  dbSNP_RS        dbSNP_Val_Status, Tumor_Sample_Barcode, Matched_Norm_Sample_Barcode,     Match_Norm_Seq_Allele1, SYMBOL_SOURCE   SIFT    PolyPhen        GMAF    BIOTYPE ENSP    DOMAINS CCDS    HGVSc   HGVSp   AFR_MAF AMR_MAF ASN_MAF EUR_MAF PUBMED are empty. 

VEP annotation goes well. What could be a problem?

part of maf file, I get:

Hugo_Symbol     Entrez_Gene_Id  Center  NCBI_Build      Chromosome      Start_Position  End_Position    Strand  Variant_Classi
Unknown 0       .       37      1       881753  881753  +       IGR     DEL     A       -       -       rs35372813      ...
Unknown 0       .       37      1       898120  898120  +       IGR     SNP     G       A       A       rs142704607     
Unknown 0       .       37      1       899427  899427  +       IGR     SNP     C       T       T       rs368133518     
Unknown 0       .       37      1       935087  935087  +       IGR     SNP     G       A       A       rs370586563     
Unknown 0       .       37      1       981235  981235  +       IGR     SNP     G       T       T       rs373631709     
Unknown 0       .       37      1       981523  981523  +       IGR     SNP     C       G       G       rs374079858     
Unknown 0       .       37      1       985465  985465  +       IGR     SNP     G       A       A       rs200384052     
Unknown 0       .       37      1       989295  989295  +       IGR     SNP     C       T       T       rs369308183     
...

**Comment by ckandoth** [comment]
Thanks for your interest. It's not the best selection of variants for a test data set - intronic or intergenic calls. I'll work on a more comprehensive test set at some points.
