### ISSUE TITLE
Add documentation and portability/flexibility for docker container

### ISSUE THREAD

**Issue by ckandoth** [mskcc/vcf2maf#70]
In reference to discussion in #64.

**Comment by adamstruck** [comment]
Here was my approach to dockerizing your tool: 

https://github.com/ohsu-computational-biology/dockerized-tools/tree/develop/vcf2maf

**Comment by ckandoth** [comment]
[More minimalist Dockerfile](https://github.com/mskcc/vcf2maf/blob/a71feb8/Dockerfile) in commit a71feb8. Still need to write some docs on how to use it.
