### ISSUE TITLE
maf2maf.pl: dbSNP_RS column is not populated 

### ISSUE THREAD

**Issue by sripakpa** [mskcc/vcf2maf#72]
Hi @ckandoth:

This is the other issue that I mentioned to you earlier during our conservation. The issue is not critical for my use-case, but I figure that I should report it anyways.

The dbSNP_RS column (column #14) is not populated in the output generated by the maf2maf.pl script.

Here is example input maf file:
[https://drive.google.com/open?id=0B0-e6kHKPsMDaTdRTVNJdTBfMms]

Here is the output from maf2maf.pl that I got:
[https://drive.google.com/open?id=0B0-e6kHKPsMDLW9vR3dUNHdLYzg]

I used the following commit of vcf2maf codeabase:

    commit 3f757be48e33a3e6c6750d599cb18e4da90d1d5a
    Merge: 876190d 11e9ed1
    Author: Cyriac Kandoth <ckandoth@gmail.com>
    Date:   Thu Aug 11 12:57:16 2016 -0400

        Merge pull request #64 from sbg/dockerizeit-1.6.7

        Adding a dockerfile using VEP 85, after 1.6.7 release.

Note that when I use vcf2maf.pl script from the same codebase (same commit), the outfile does contain data in dbSNP_RS column. So I suspect this is an issue with maf2maf.pl script.

**Comment by ckandoth** [comment]
Now fixed in 7689356. I'll run some more tests and tag it as release `v1.6.8` shortly.
