### ISSUE TITLE
Add "ExAC_AF_Adj" column to vcf2maf and maf2maf outfile

### ISSUE THREAD

**Issue by sripakpa** [mskcc/vcf2maf#75]

**Comment by ckandoth** [comment]
I'll add this into release `v1.7` in ~1 week, along with the recent commit 25962c4 that adds Entrez IDs. There will be some column # shuffling, which is more appropriate in a `1.x.0` release.

**Comment by sripakpa** [comment]
Great! :)

**Comment by ckandoth** [comment]
I went ahead and did this in c295c11. Feel free to use the `master` branch for now. I'm still pondering over a `v1.7` release.
