### ISSUE TITLE
Issues while running vcf2maf on Varscan2 VCF files

### ISSUE THREAD

**Issue by anishbhaswanth** [mskcc/vcf2maf#76]
#Hi,

I'm running vcf2maf.pl on Varscan2 VCF files. 

Here is my command:
```
vcf2maf.pl --input-vcf TS-02.snp.vcf --output-maf TS-02.snp.vep.maf --tumor-id TS-02T --normal-id TS-02N --vcf-tumor-id TUMOR --vcf-normal-id NORMAL --vep-path /packages/Tools/ensembl-tools-release-85/scripts/variant_effect_predictor/ --vep-data ~/Refs/VEP/ 
```

But, it gives me only warnings and the resulting maf file is empty. Here are couple of warnings:
```
WARNING: Could not fetch sub-slice from Y:13842808-13842808(1) on line 1013
WARNING: Specified reference allele G does not match Ensembl reference allele on line 1013
WARNING: Could not fetch sub-slice from Y:14475374-14475374(1) on line 1014
WARNING: Specified reference allele C does not match Ensembl reference allele on line 1014
```

I ran Varscan2 using UCSC reference genome. But the cache I have downloaded is Ensembl GRCh37 and I'm assuming that's causing the errors/warnings? 

Can you tell me how to use vcf2maf when I have UCSC reference genome? I tried looking online, but I could not find any documentation regarding it.

PS: The tool seems to work fine with the example data given. So, I believe the installation worked fine.

Thanks
Anish.

**Comment by ckandoth** [comment]
Thanks for your interest in `vcf2maf`, Anish. The very latest release has some checks to help debug such "reference mismatch" problems. If your VCF was generated with UCSC's hg19 FASTA, then use that same FASTA file with `vcf2maf --ref-fasta`.

**Comment by anishbhaswanth** [comment]
Thank you! That helped.
