### ISSUE TITLE
Incorrect ref mismatch for long deletions

### ISSUE THREAD

**Issue by kpjonsson** [mskcc/vcf2maf#80]
`cmo_maf2maf` incorrectly states that long deletions do not match the reference and thus fails to annotate these. Might be an issue with `samtools faidx` usage.

**Comment by ckandoth** [comment]
Danke schön! Fixed in 735c1f7 which replaces the v1.6.9 tag. Hopefully this is the last time I need to make a hotfix without update the release ID.
