### ISSUE TITLE
NAs in multiple columns, including Mutation_Status

### ISSUE THREAD

**Issue by vsvinti** [mskcc/vcf2maf#81]
Hi there

Maybe I'm misunderstanding what I'm wanting to get out of a maf file, but I was hoping I would be able to flag which variants are somatic (presumably by extracting Somatic keywords from the Mutation_Status column). However, I have a lot of columns with NAs (see below). While presumably validation status etc is based on lacking data for this, I am not sure about the others. 

Given that I have alleles for tumors and normals, I thought the vcf2maf takes care of the 'subtraction' for me, so I can easily identify somatic only variants. Am I completely off track in my interpretation?

<pre>
Tumor_Validation_Allele1
Tumor_Validation_Allele2
Match_Norm_Validation_Allele1
Match_Norm_Validation_Allele2
Verification_Status
Validation_Status
Mutation_Status
Sequencing_Phase
Sequence_Source
Validation_Method
Score
BAM_File
Sequencer
Tumor_Sample_UUID
Matched_Norm_Sample_UUID
</pre>

Thanks
Vicky

**Comment by ckandoth** [comment]
Hi Vicky, have you seen the official [MAF specs](https://wiki.nci.nih.gov/x/eJaPAQ)? I link to it in [my doc here](https://github.com/mskcc/vcf2maf/blob/v1.6.9/docs/vep_maf_readme.txt) describing all the columns.

All the columns you listed are unique to TCGA - the creators of the MAF spec. `vcf2maf` will make no attempt to give them values. If you use `maf2maf` on a TCGA MAF, it will simply copy over the values under these columns in the input MAF, but it will modify columns related to variant effect - like `Variant_Classification`, `Variant_Type`, `dbSNP_RS`, etc.

Back to your need for somatic variants - Both `vcf2maf` and `maf2maf` simply use [VEP](http://useast.ensembl.org/info/docs/tools/vep/index.html) to annotate the effect that variants have on the genes that they overlap. Neither tool tries to distinguish between somatic or germline variants, but do provide data that might help remove known germline variants and artifacts/errors. In [my doc here](https://github.com/mskcc/vcf2maf/blob/v1.6.9/docs/vep_maf_readme.txt#L99) there are also some notes on how to distinguish cancer driver mutations from passenger events.

Can you explain the overarching goals in your project? I recall you're working with mouse.

**Comment by ckandoth** [comment]
In issue #78 you mentioned you used mutect2 from GATK. That is the tool that is doing the tumor-normal allele subtraction and a whole bunch of complicated false-positive filtering, before generating the VCF that you ran through vcf2maf. The `FILTER` column in the VCF says `PASS` for a variant, if MuTect2 believes it is a somatic mutation, and it has passed all those FP filters. The VCF may also contain the non-PASSed calls, which will have different reasons for being filtered out, specified under the same `FILTER` column. `vcf2maf` will copy over the values under this column into the resulting MAF file, so you can skim through those. The explanations for `FILTER` tags are usually explained in the VCF headers.

**Comment by vsvinti** [comment]
Hi @ckandoth , thanks so much for your response. It's been a while since I read the maf specs, and I didn't realise those columns are TCGA related. I did only use PASS variants from mutect, and filter based on impact etc. But what confused me is why we have a tumor and a normal column. I thought that maybe it is still reporting all of them. Having a closer look, I can see they are all somatic calls but they simply have both tumor + normal columns to outline what the allele is in each of these.

Thanks very much for your feedback, and sorry that this wasn't actually a vcf2maf related issue!
Best
Vicky

**Comment by ckandoth** [comment]
Correct. Glad it's clear now. Somatic variant calling is not simply a tumor minus normal subtraction. There are many false-positives related to coverage differences, paralogous mis-alignments, low-level contamination, amplification bias, strand bias, etc. MuTect tries its best to handle a lot of these issues, and reports a VCF with stats on each variant, as seen in both tumor and normal samples. These stats are stored in `FORMAT`ted genotype columns, where the column name is usually the sample IDs. In the VCF you shared in issue #78, these columns were simply named `TUMOR` and `NORMAL`, which seems unusual. Either way, be sure to use `--vcf-tumor-id` and `--vcf-normal-id` to specify these column names, that differ from the actual sample IDs you specify in `--tumor-id` and `--normal-id`. Doing this correctly will get you proper REF/ALT allele counts seen in both tumor and normal samples, which are valuable in studying tumor heterogeneity, and identifying clonal initiating events.

I'll close this issue. If you have general questions, try [biostars.org](https://www.biostars.org). I'm usually responsive to questions with tags like `cancer` and `somatic`.
