### ISSUE TITLE
Does vcf2maf v1.6.9 support ensembl release 86?

### ISSUE THREAD

**Issue by hongenxu** [mskcc/vcf2maf#84]
Hi Dr. Kondoth, 

I am working on chicken tumor, and release 86 has a newer chicken gene build. I want to try ensembl release 86 but not succeed. I want to make sure weather VCF2maf support ensembl 86?

Thanks, 
Hongen

**Comment by ckandoth** [comment]
I've released v1.6.10 which adds support for Ensembl release v86. Also note the [new gist](https://gist.github.com/ckandoth/f265ea7c59a880e28b1e533a6e935697) with instructions for properly installing VEP v86 in a way that vcf2maf can use it.
