### ISSUE TITLE
Option cache   --cache-version missing 

### ISSUE THREAD

**Issue by kjnousia** [mskcc/vcf2maf#86]
Hi,

I have data whose variant calling have been performed with respect to reference Ensembl version 73. I have had  VEP version 85 installed because the installation script for release 73 points to an empty folder. Luckily an older cache  (ftp://ftp.ensembl.org/pub/release-73/variation/VEP/homo_sapiens_refseq_vep_73.tar.gz) was found and installed to path share/apps/vcf2maf/1.6.9/vep_data/73. The same folder contains the current caches in directories 85_GRCh37 and  85_GRCh38. Using VEP 73 cache does not work:

perl /share/apps/vcf2maf/1.6.9/vcf2maf.pl --input-vcf my.vcf --output-maf test.maf.txt --tumor-id tumor --vcf-normal-id normal --cache-version 73 --vcf-tumor-id tumor --vep-path /share/apps/vcf2maf/1.6.9/vep_path --vep-data  /share/apps/vcf2maf/1.6.9/vep_data/ --ref-fasta myData/Homo_sapiens.GRCh37.73.dna.chr.fa             
Unknown option: cache-version
Usage:
     perl vcf2maf.pl --help
     perl vcf2maf.pl --input-vcf WD4086.vcf --output-maf WD4086.maf --tumor-id WD4086 --normal-id NB4086

Options:
     --input-vcf      Path to input file in VCF format
     --output-maf     Path to output MAF file [Default: STDOUT]
     --tumor-id       Tumor_Sample_Barcode to report in the MAF [TUMOR]
     --normal-id      Matched_Norm_Sample_Barcode to report in the MAF [NORMAL]
     --vcf-tumor-id   Tumor sample ID used in VCF's genotype columns [--tumor-id]
     --vcf-normal-id  Matched normal ID used in VCF's genotype columns [--normal-id]
     --custom-enst    List of custom ENST IDs that override canonical selection
     --vep-path       Folder containing variant_effect_predictor.pl [~/vep]
     --vep-data       VEP's base cache/plugin directory [~/.vep]
     --vep-forks      Number of forked processes to use when running VEP [4]
     --ref-fasta      Reference FASTA file [~/.vep/homo_sapiens/85_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz]
     --species        Ensembl-friendly name of species (e.g. mus_musculus for mouse) [homo_sapiens]
     --ncbi-build     NCBI reference assembly of variants MAF (e.g. GRCm38 for mouse) [GRCh37]
     --cache-version  Version of offline cache to use with VEP (e.g. 75, 82, 85) [Default: Installed version]
     --maf-center     Variant calling center to report in MAF [.]
     --retain-info    Comma-delimited names of INFO fields to retain as extra columns in MAF []
     --min-hom-vaf    If GT undefined in VCF, minimum allele fraction to call a variant homozygous [0.7]
     --help           Print a brief help message and quit
     --man

Perhaps because parse function of the script misses the option

# Parse options and print usage if there is a syntax error, or if usage was explicitly requested
my ( $man, $help ) = ( 0, 0 );
my ( $input_vcf, $output_maf, $custom_enst_file );
my ( $vcf_tumor_id, $vcf_normal_id );
GetOptions(
    'help!' => \$help,
    'man!' => \$man,
    'input-vcf=s' => \$input_vcf,
    'output-maf=s' => \$output_maf,
    'tumor-id=s' => \$tumor_id,
    'normal-id=s' => \$normal_id,
    'vcf-tumor-id=s' => \$vcf_tumor_id,
    'vcf-normal-id=s' => \$vcf_normal_id,
    'custom-enst=s' => \$custom_enst_file,
    'vep-path=s' => \$vep_path,
    'vep-data=s' => \$vep_data,
    'vep-forks=s' => \$vep_forks,
    'ref-fasta=s' => \$ref_fasta,
    'species=s' => \$species,
    'ncbi-build=s' => \$ncbi_build,
    'maf-center=s' => \$maf_center,
    'retain-info=s' => \$retain_info,
    'min-hom-vaf=s' => \$min_hom_vaf
)

However, if the option is added to the list ('cache-version=s' => \$cache_version,) vcf2maf do not still work:

STATUS: Running VEP and writing to: my.vep.vcf
2016-10-14 15:56:36 - Read existing cache info
2016-10-14 16:00:40 - Loaded plugin: ExAC
2016-10-14 16:00:40 - Starting...
2016-10-14 16:00:40 - Detected format of input file as vcf
2016-10-14 16:00:42 - Read 5000 variants into buffer
2016-10-14 16:00:42 - Checking for existing variations
2016-10-14 16:00:52 - Reading transcript data from cache and/or database
2016-10-14 16:01:24 - Retrieved 17909 transcripts (0 mem, 18741 cached, 0 DB, 832 duplicates)
2016-10-14 16:01:24 - Reading regulatory data from cache and/or database
2016-10-14 16:01:57 - Retrieved 99272 regulatory features (0 mem, 99296 cached, 0 DB, 24 duplicates)
2016-10-14 16:01:57 - Analyzing chromosome 1
2016-10-14 16:01:58 - Analyzing variants
2016-10-14 16:02:08 - Analyzing RegulatoryFeatures
2016-10-14 16:02:10 - Analyzing MotifFeatures
Use of uninitialized value in split at /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Funcgen/BindingMatrix.pm line 247.
Use of uninitialized value $tmp[0] in pattern match (m//) at /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Funcgen/BindingMatrix.pm line 248.

-------------------- EXCEPTION --------------------
MSG: Matrix MA0093.1 has an invalid number of lines:
	
STACK Bio::EnsEMBL::Funcgen::BindingMatrix::_validate_matrix /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Funcgen/BindingMatrix.pm:259
STACK Bio::EnsEMBL::Funcgen::BindingMatrix::_build_matrix /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Funcgen/BindingMatrix.pm:250
STACK Bio::EnsEMBL::Funcgen::BindingMatrix::length /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Funcgen/BindingMatrix.pm:451
STACK Bio::EnsEMBL::Funcgen::BindingMatrix::is_position_informative /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Funcgen/BindingMatrix.pm:421
STACK Bio::EnsEMBL::Variation::MotifFeatureVariationAllele::in_informative_position /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Variation/MotifFeatureVariationAllele.pm:169
STACK Bio::EnsEMBL::Variation::Utils::VEP::mfva_to_line /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Variation/Utils/VEP.pm:2803
STACK Bio::EnsEMBL::Variation::Utils::VEP::vfoa_to_line /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Variation/Utils/VEP.pm:2545
STACK Bio::EnsEMBL::Variation::Utils::VEP::vf_to_consequences /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Variation/Utils/VEP.pm:2224
STACK Bio::EnsEMBL::Variation::Utils::VEP::rejoin_variants /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Variation/Utils/VEP.pm:1785
STACK Bio::EnsEMBL::Variation::Utils::VEP::vf_list_to_cons /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Variation/Utils/VEP.pm:1507
STACK Bio::EnsEMBL::Variation::Utils::VEP::get_all_consequences /share/apps/vcf2maf/1.6.9/vep_path/Bio/EnsEMBL/Variation/Utils/VEP.pm:1361
STACK main::main /share/apps/vcf2maf/1.6.9/vep_path/variant_effect_predictor.pl:295
STACK toplevel /share/apps/vcf2maf/1.6.9/vep_path/variant_effect_predictor.pl:149
Date (localtime)    = Fri Oct 14 16:02:11 2016
Ensembl API version = 85
---------------------------------------------------

ERROR: Failed to run the VEP annotator!
Command: /share/apps/easybuild/software/Perl/5.10.1-goolf-triton-2016a/bin/perl /share/apps/vcf2maf/1.6.9/vep_path/variant_effect_predictor.pl --species homo_sapiens --assembly GRCh37 --offline --no_progress --no_stats --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --pubmed --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --minimal --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir /share/apps/vcf2maf/1.6.9/vep_data/ --fasta myData/Homo_sapiens.GRCh37.73.dna.chr.fa --input_file  my.vcf --output_file my.vep.vcf --cache_version 73 --polyphen b --gmaf --maf_1kg --maf_esp --regulatory --plugin ExAC,/share/apps/vcf2maf/1.6.9/vep_data//ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz

Please, help me to convert my vcf file to maf. My plan is to use the file as input for genome-music.

Best Regards,
Kari Nousiainen

**Comment by ckandoth** [comment]
Hi Kari. Thanks for this detailed bug report. You are correct that `--cache-version` option was missing. This has now been fixed in 5612745, available in the latest master branch. Closing this issue.

If variant calling was done on `GRCh37`, you can certainly use Ensembl release 85 for annotation. You don't need to fall back to release 73. We can continue this discussion over email. I will close this issue.

**Comment by kjnousia** [comment]
Hi,

Thank for your kind help.

I just wonder which reference to use in this case. New vep/homo_sapiens/85_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz included in VEP or the old Homo_sapiens.GRCh37.73.dna.chr.fa to which aligments have been done.

Kari




________________________________
Lähettäjä: Cyriac Kandoth [notifications@github.com]
Lähetetty: 14. lokakuuta 2016 17:09
Vastaanottaja: mskcc/vcf2maf
Kopio: Nousiainen Kari; Author
Aihe: Re: [mskcc/vcf2maf] Option cache --cache-version missing (#86)


Hi Kari. Thanks for this detailed bug report. You are correct that --cache-version option was missing. This has now been fixed in 5612745<https://github.com/mskcc/vcf2maf/commit/56127451154c47e9a9bccff7a244eefbcb5ae9e9>, available in the latest master branch. Closing this issue.

If variant calling was done on GRCh37, you can certainly use Ensembl release 85 for annotation. You don't need to fall back to release 73. We can continue this discussion over email. I will close this issue.

**Comment by ckandoth** [comment]
You can use either one. They should be identical.

Note that the file name `Homo_sapiens.GRCh37.73.dna.chr.fa` is unusual, and not something you can download directly from `ftp://ftp.ensembl.org/pub/release-73/fasta/homo_sapiens/dna/`. So it's possible that it was manually prepared by someone.

**Comment by kjnousia** [comment]
Hi,

Thank you very much. I  appreciate your insight.

Kari Nousiainen
________________________________
Lähettäjä: Cyriac Kandoth [notifications@github.com]
Lähetetty: 14. lokakuuta 2016 17:40
Vastaanottaja: mskcc/vcf2maf
Kopio: Nousiainen Kari; Author
Aihe: Re: [mskcc/vcf2maf] Option cache --cache-version missing (#86)


You can use either one. They should be identical.

Note that the file name Homo_sapiens.GRCh37.73.dna.chr.fa is unusual, and not something you can download directly from ftp://ftp.ensembl.org/pub/release-73/fasta/homo_sapiens/dna/. So it's possible that it was manually prepared by someone.
