### ISSUE TITLE
Many errors of using uninitialized value produced by vcf2maf

### ISSUE THREAD

**Issue by kjnousia** [mskcc/vcf2maf#87]
Use of uninitialized value in hash element at vcf2maf.pl line 574, <GEN2> line 6224.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 658, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 659, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 660, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 660, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 661, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 661, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 662, <GEN2> line 6224.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 663, <GEN2> line 6224.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 664, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 664, <GEN2> line 6224.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 665, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 665, <GEN2> line 6224.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 666, <GEN2> line 6224.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 667, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 668, <GEN2> line 6224.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 669, <GEN2> line 6224.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 670, <GEN2> line 6224.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 671, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 672, <GEN2> line 6224.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 673, <GEN2> line 6224.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 674, <GEN2> line 6224.
One run produces plenty of errors e.g following:
Use of uninitialized value $effect in string eq at vcf2maf.pl line 675, <GEN2> line 6224.

Use of uninitialized value in hash element at vcf2maf.pl line 574, <GEN2> line 21623.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 658, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 659, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 660, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 660, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 661, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 661, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 662, <GEN2> line 21623.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 663, <GEN2> line 21623.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 664, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 664, <GEN2> line 21623.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 665, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 665, <GEN2> line 21623.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 666, <GEN2> line 21623.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 667, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 668, <GEN2> line 21623.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 669, <GEN2> line 21623.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 670, <GEN2> line 21623.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 671, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 672, <GEN2> line 21623.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 673, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 674, <GEN2> line 21623.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 675, <GEN2> line 21623.
Use of uninitialized value in hash element at vcf2maf.pl line 574, <GEN2> line 50829.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 658, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 659, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 660, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 660, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 661, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 661, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 662, <GEN2> line 50829.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 663, <GEN2> line 50829.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 664, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 664, <GEN2> line 50829.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 665, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 665, <GEN2> line 50829.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 666, <GEN2> line 50829.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 667, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 668, <GEN2> line 50829.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 669, <GEN2> line 50829.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 670, <GEN2> line 50829.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 671, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 672, <GEN2> line 50829.
Use of uninitialized value $effect in pattern match (m//) at vcf2maf.pl line 673, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 674, <GEN2> line 50829.
Use of uninitialized value $effect in string eq at vcf2maf.pl line 675, <GEN2> line 50829.

**Comment by ckandoth** [comment]
These are warnings and usually benign. But it indicates that something in the input file, is not as expected. If you can give me a sample variant in VCF format, I can debug.

**Comment by ckandoth** [comment]
Closing issue. But please reopen if you continue to see such warnings.

**Comment by knightjimr** [comment]
I am getting this error for samples I am running.  Attached is a VCF file with a variant that triggers the error (on version 1.6.14).  This variant has multiple alt alleles, which may be the root of the issue.

Note, I had to change the name to error.vcf.txt, because .vcf files are not accepted.

[error.vcf.txt](https://github.com/mskcc/vcf2maf/files/1250241/error.vcf.txt)

**Comment by ckandoth** [comment]
@knightjimr Created a separate issue for your thing - https://github.com/mskcc/vcf2maf/issues/135
