### ISSUE TITLE
ExAC frequencies are missing for some indels in the maf2maf output

### ISSUE THREAD

**Issue by ShwetaCh** [mskcc/vcf2maf#91]
Hi Cyriac, 

In the maf2maf VEP output, indels such as `5       56177848        TCAA    T` are not getting populated with ExAC frequencies. However, the ExAC vcf `ExAC_nonTCGA.r0.3.1.sites.vep.vcf` does have this allele present in the file but in a non-normalized format : `5  56177848    .   TCAACAACAACAA   TCAACAACAA`, and probably why it is not getting recognized. 

-Shweta

**Comment by ckandoth** [comment]
Thanks for reporting this. This seems to be a bug in the ExAC plugin. See [this line in their code](https://github.com/Ensembl/VEP_plugins/blob/release/86/ExAC.pm#L212). A fix seems simple, and we can send them a pull request. For each variant, tabix is used to pull overlapping lines in the ExAC VCF, and alleles are loaded in a list called `@vcf_alleles`. These are compared one-by-one against the input variant allele. But before that, they need to be normalized using a simple regex, or something like `bcftools norm`.

**Comment by ckandoth** [comment]
This is now handled in 86e58e3
