### ISSUE TITLE
hg19 issue

### ISSUE THREAD

**Issue by mforde84** [mskcc/vcf2maf#95]
Is it possible to use vcf2maf with hg19 reference fastas from UCSC or GENCODE? I have VCF files were were produced with those particular references, however VEP won't recognize them after following the gist documentation. In particular I get the error:

$ perl vcf2maf.pl --input-vcf ../mutect-example.vcf --output-maf test.maf
ERROR: Make sure that ref-fasta is the same genome build as your VCF: /home/blik/.vep/homo_sapiens/86_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz

**Comment by ckandoth** [comment]
Note that MAF specs use the older GRCh37 chromosome names without those `chr` prefixes. But it's not a big deal if you use `chr` prefixes in MAF format. You have two options:
```bash
# Use --ref-fasta to point your own hg19 fasta, so that your output MAF also contains hg19 loci:
perl vcf2maf.pl --input-vcf test.vcf --output-maf test.maf --ref-fasta /path/to/my/hg19.fa
```
```bash
# Use --remap-chain with the provided chain file to convert your hg19 coordinates to GRCh37:
perl vcf2maf.pl --input-vcf test.vcf --output-maf test.maf --remap-chain data/hg19_to_GRCh37.chain
```
